-- Trip Shed VVH Step 5 exact GC source checklist restoration
-- Adds source-restored GC template and disables entry on abbreviated template 1; historical records keep template_id=1.
START TRANSACTION;
UPDATE div_trip_inspection_templates SET entry_enabled=0 WHERE id=1 AND inspection_type='GC';
INSERT INTO div_trip_inspection_templates(inspection_type,version_no,title,enabled,entry_enabled) VALUES('GC','VVH-2025-08-SOURCE','General Checking of Locos — approved source VVH-2025-08',1,1);
SET @gc_source_template_id = LAST_INSERT_ID();
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','1','Check loco Log Book for defect entries made by Crew.','लोको लॉग बुक में क्रू द्वारा दर्ज की गई दोष प्रविष्टियों की जाँच करें।',NULL,1,1); -- source_row 3
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','2','Checking of fault massage on DDS.','DDS पर फॉल्ट संदेश की जाँच करें।',NULL,2,1); -- source_row 4
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','3','Checking of safety item such as head light from both position of DC to DC converter, flasher light on both position, Maker light, Horn, wipers, SPM Floppy, VCD, Fire extinguisher, Wooden wedges, safety clamp, Cab lights, Gauges lights etc','हेडलाइट (डीसी टू डीसी कन्वर्टर के दोनों पोजीशन से), फ्लैशर लाइट दोनों पोजीशन में, मेकर लाइट, हॉर्न, वाइपर, SPM फ्लॉपी, VCD, अग्निशामक, लकड़ी के वेज, सेफ्टी क्लैम्प, कैब लाइट, गेज लाइट आदि जैसे सभी सुरक्षा उपकरणों की जाँच करें।',NULL,3,1); -- source_row 5
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','4','Check air leakage from any pipe in HT compartment, Machine room, Pneumatic Panel, Under gear etc.','HT कम्पार्टमेंट, मशीन रूम, न्यूमैटिक पैनल, अंडर गियर आदि में किसी भी पाइप से वायु रिसाव के लिए जांच करें।',NULL,4,1); -- source_row 6
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','5','BP/FP, MR pressure creation and testing in working cab after putting dummy plate on palm. Also check A-9 & SA-9 pressure.','पाम पर डमी प्लेट लगाने के बाद कार्यशील कैब में BP/FP, MR दबाव सृजन और परीक्षण करें। साथ ही A-9 और SA-9 दबाव की भी जांच करें।',NULL,5,1); -- source_row 7
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','6','Check loco brake power on 80% of continuous current loco should not be move in both forward/reverse direction. If required brake adjustment to be done.','लोको के ब्रेक क्षमता की जांच करे। 80 प्रतिशत लगातार विद्युत प्रभाव के लोको आगे या पीछे की दिशा में हिलना नही चाहिए। यदि आवश्यक हो तो ब्रेक का समायोजन किया जाना चाहिए।',NULL,6,1); -- source_row 8
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','7','Check oil level of GR, TFP, SR & check for any oil leakage from GR, TFP, SR, Conservators, Radiator, pumps etc.','GR, TFP, SR का तेल स्तर जांचें और GR, TFP, SR, कंजरवेटर, रेडिएटर, पंप आदि से किसी भी तेल रिसाव की जांच करें।',NULL,7,1); -- source_row 9
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','8','Pantograph raising & lowering from both the cabs.','दोनों कैब से पेंटोग्राफ उठाने और नीचे करने की जाँच करें।',NULL,8,1); -- source_row 10
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','9','HT testing of loco to be done.','लोको का HT परीक्षण करें।',NULL,9,1); -- source_row 11
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','10','Check the working of AUX. machines for observing any abnormal sound.','AUX मशीनों के कार्य की जाँच करें और किसी भी असामान्य ध्वनि का निरीक्षण करें।',NULL,10,1); -- source_row 12
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','11','Check the working of both HLC.','दोनों HLC के कार्य की जाँच करें।',NULL,11,1); -- source_row 13
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'General / सामान्य','12','Check the working of Cab AC, Cab Heaters in both cabs.','दोनों कैब में कैब AC और कैब हीटर के कार्य की जाँच करें।',NULL,12,1); -- source_row 14
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','13','Check Buffer for any Crack/Damages and ensure intactness of foundation bolts.','बफर में किसी भी दरार/क्षति की जाँच करें और फाउंडेशन बोल्ट की मजबूती सुनिश्चित करें।',NULL,13,1); -- source_row 16
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','14','Ensure intactness of All Nut-Bolls and Locking Bolt of Cattle Guard and Rail Guard.','सभी नट-बोल्ट और कैटल गार्ड व रेल गार्ड के लॉकिंग बोल्ट की मजबूती सुनिश्चित करें।',NULL,14,1); -- source_row 17
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','15','Check All Dampers and Ensure their foundation bracket with all Nut Bolts are Intact','सभी डैम्पर की जाँच करें और उनके फाउंडेशन ब्रैकेट के सभी नट-बोल्ट सही स्थिति में हों यह सुनिश्चित करें।',NULL,15,1); -- source_row 18
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','16','Check Wheel Set Guide Rods for any crack/Damages.','व्हील सेट गाइड रॉड में किसी भी दरार/क्षति की जाँच करें।',NULL,16,1); -- source_row 19
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','17','Visual Check of crack in Bogie frame & Brake Rigging Parts especially brake Hangers. Also check the Trunion assembly with safety straps in WAP-4 Locos.','WAP-4 लोकोमोटिव्स में बोगी फ्रेम और ब्रेक रिगिंग पार्ट्स, विशेषकर ब्रेक हैंगर में दरारों की दृश्य जांच करें। साथ ही ट्रुनियन असेंबली और सुरक्षा पट्टियों की भी जांच करें।',NULL,17,1); -- source_row 20
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','18','Check Primary and Secondary Spring for Crack, if any.','प्राइमरी और सेकेंडरी स्प्रिंग में दरार की जाँच करें।',NULL,18,1); -- source_row 21
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','19','Check Battery Box Foundation bracket for any crack and ensure intactness of all Nut Bolts.','बैटरी बॉक्स फाउंडेशन ब्रैकेट में दरार की जाँच करें और सभी नट-बोल्ट सही स्थिति में हों यह सुनिश्चित करें।',NULL,19,1); -- source_row 22
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','20','Check the Axle Box, its liners, Equalizer Beam, safety Bracket and its cotter Pin.','एक्सल बॉक्स, उसके लाइनर, इक्वलाइज़र बीम, सेफ्टी ब्रैकेट और कॉटर पिन की जाँच करें।',NULL,20,1); -- source_row 23
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','21','Check the Intactness of Sand Box & ensure working of sanders.','सैंड बॉक्स की मजबूती और सैंडर के कार्य की जाँच करें।',NULL,21,1); -- source_row 24
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','22','Visual check the condition of side bearers.','साइड बेयरर्स की स्थिति का दृष्टिगत निरीक्षण करें।',NULL,22,1); -- source_row 25
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','23','Measure CBC height from rail level.','CBC की ऊँचाई रेल स्तर से मापें।',NULL,23,1); -- source_row 26
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','24','Ensure Closing and opening of both side CBC to be ensured.','दोनों ओर के CBC का खुलना और बंद होना सुनिश्चित करें।',NULL,24,1); -- source_row 27
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Side Gear / साइड गियर','25','Intactness of CBC yoke Pin locking bolts to be ensured.','CBC योके पिन लॉकिंग बोल्ट की मजबूती सुनिश्चित करें।',NULL,25,1); -- source_row 28
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','26','Check the Traction Link assembly, Aclathan ring, TBU/PBU in (WAP-5, WAG-9 Loco), Brake disc (WAP-5 Loco), Axle guide rod & Spheri bloc for any damages & crack and Ensure intactness of all nut bolts.','ट्रैक्शन लिंक असेंबली, ऐक्लाथन रिंग, TBU/PBU (WAP-5, WAG-9 लोको में), ब्रेक डिस्क (WAP-5 लोको में), एक्सल गाइड रॉड और स्फेरी ब्लॉक में किसी भी प्रकार की क्षति एवं दरार की जांच करें तथा सभी नट-बोल्ट की सुदृढ़ता सुनिश्चित करें।',NULL,26,1); -- source_row 30
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','27','Check tightness of both end cover bolts of Traction motor and intactness of MSU Bolt & Safety Sling, Traction Motor Torque arm for any crack, tightness of bolts of Torque arms & Traction Motor Holder plate.','ट्रैक्शन मोटर के दोनों सिरों के कवर बोल्ट की कसावट, एमएसयू बोल्ट एवं सेफ़्टी स्लिंग की सुदृढ़ता, ट्रैक्शन मोटर टॉर्क आर्म में किसी भी प्रकार की दरार, टॉर्क आर्म्स एवं ट्रैक्शन मोटर होल्डर प्लेट के बोल्ट की कसावट की जांच करें।',NULL,27,1); -- source_row 31
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','28','Check all Gear Case for Oil level Oil Leakage and ensure intactness of Gear Case Bolts.','सभी गियर केस के तेल स्तर, तेल रिसाव की जाँच करें और गियर केस बोल्ट की मजबूती सुनिश्चित करें।',NULL,28,1); -- source_row 32
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','29','Ensure that safety slings are available at Compressors and traction motors.','कम्प्रेसर और ट्रैक्शन मोटर में सेफ्टी स्लिंग की उपलब्धता सुनिश्चित करें।',NULL,29,1); -- source_row 33
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','30','Check welding Crackness of hanging Compressor Three legs & lightness of its Nut-Bolt & intactness of safety sling in 3phase Loco.','हैंगिंग कम्प्रेसर के तीन पैरों में वेल्डिंग क्रैकनेस, उसके नट-बोल्ट की कसावट और 3 फेज़ लोको में सेफ्टी स्लिंग की मजबूती की जाँच करें।',NULL,30,1); -- source_row 34
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','31','Check Air Dryer Mounting plate for any crack and ensure tightness of all Nut Bolts','एयर ड्रायर माउंटिंग प्लेट में दरार की जाँच करें और सभी नट-बोल्ट की कसावट सुनिश्चित करें।',NULL,31,1); -- source_row 35
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','32','Checking of TM mounting arrangement, TM lugs, Sandwich Assembly (Vertical, Horizontal) & Its Split Pin, any other crack.','टीएम माउंटिंग अरेंजमेंट, टीएम लग्स, सैंडविच असेंबली (वर्टिकल, हॉरिजॉन्टल) एवं उसके स्प्लिट पिन की जाँच करें तथा किसी अन्य प्रकार की दरार की भी जाँच करें।',NULL,32,1); -- source_row 36
INSERT INTO div_trip_inspection_template_items(template_id,section_name,item_no,label_en,label_hi,standard_value,sort_order,is_required) VALUES(@gc_source_template_id,'Under Gear / अंडर गियर','33','Check MR Tank & SL foundation and supporting brackets for any crack and ensure intactness of all Nut Bolts.','एम.आर. टैंक एवं एस.एल. की नींव तथा सहायक ब्रैकेट में किसी भी प्रकार की दरार की जाँच करें और सभी नट-बोल्ट की मजबूती सुनिश्चित करें।',NULL,33,1); -- source_row 37
COMMIT;
