-- Trip Shed VVH Step 4 source-row/brake-table resolution
-- Applies resolved source text and marks brake table reference rows non-required.
START TRANSACTION;
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='iv', label_en='Check the working of head light with DC-DC converter positions', label_hi='डीसी-डीसी कन्वर्टर की विभिन्न स्थितियों के साथ हेड लाइट के कार्य की जाँच करें। अ) मोड-1 ब) मोड-2', standard_value='Both position working normal', is_required=1 WHERE template_id=346 AND sort_order=29; -- source_row 36
UPDATE div_trip_inspection_template_items SET section_name='Pantograph & Roof Equipments', item_no='i', label_en='inspect the entire upper structure of the pantograph assembly and check that the assembly horn, wear strip and support assembly have no cracks.', label_hi='पैन्‍टोग्राफ असेंबली के पूरे ऊपरी ढॉचे की विजुअल जॉच करें तथा जॉच करें कि असेम्‍बली हॉर्न, विअर स्‍ट्रीप तथा सपोर्ट असेम्‍बली में कोई क्रेक नहीं।', standard_value='No Crack', is_required=1 WHERE template_id=346 AND sort_order=35; -- source_row 44
UPDATE div_trip_inspection_template_items SET section_name='Pantograph & Roof Equipments', item_no='vi', label_en='check for any cracks.', label_hi='फुट माऊंटिग इंसुलेटर को साफ करें और चेक करे कि कोई क्रेक तो नहीं है।', standard_value='Clean/No crack', is_required=1 WHERE template_id=346 AND sort_order=40; -- source_row 49
UPDATE div_trip_inspection_template_items SET section_name='Pantograph & Roof Equipments', item_no='viii', label_en='Check upper thrust of both the pantograph. IR03- On 7.0Kgf, Panto pan should not leave OHE while on 7.5Kgf, panto pan should leave OHE by a paper gap between OHE & Panto pan. HRPT- After putting 7.0Kgf, pull the panto pan towards lower side, it must be stop wherever pulling force removed. Similarly, during application of upper force, Panto pan should stop wherever upper force removed.', label_hi='दोनों पेंटोग्राफ के ऊपरी थ्रस्ट की जाँच करें। दोनों पैंटोग्राफ की अपर थ्रस्ट की जांच करें। IR03 - 7.0 किलोग्राम-फोर्स (Kgf) पर पैंटो पैन को ओएचई (OHE) से अलग नहीं होना चाहिए, जबकि 7.5 किलोग्राम-फोर्स (Kgf) पर पैंटो पैन और ओएचई के बीच कागज़ की मोटाई जितना अंतर आ जाना चाहिए। HRPT - 7.0 किलोग्राम-फोर्स (Kgf) लगाने के बाद पैंटो पैन को नीचे की ओर खींचें, खींचने की ताकत हटते ही पैंटो पैन को वहीं रुक जाना चाहिए। इसी प्रकार, जब ऊपर की ओर बल लगाया जाए, तो बल हटते ही पैंटो पैन को वहीं रुक जाना चाहिए।', standard_value='7.0 किलोग्राम / 7.0 kgf', is_required=1 WHERE template_id=346 AND sort_order=42; -- source_row 51
UPDATE div_trip_inspection_template_items SET section_name='Pantograph & Roof Equipments', item_no='ix', label_en='Ensure PRV setting of HRPT Pantograph is within limit. Ref:- RDSO letter no. No. EL/2.2.1/High Reach/Faiveley)', label_hi='सुनिश्चित करें कि एचआरपीटी पैंटोग्राफ की पीआरवी सेटिंग सीमा के भीतर है।', standard_value='Within prescribed PRV setting limit', is_required=1 WHERE template_id=346 AND sort_order=43; -- source_row 52
UPDATE div_trip_inspection_template_items SET section_name='Pantograph & Roof Equipments', item_no='xiv', label_en='Check ET 1 & 2 for proper gap and clean it with polish paper.', label_hi='ई टी-1 व ई टी-2 के गेप नापे व पाॅलीश पेपर से साफ करें ।', standard_value='ET-1: 210 ± 5.0 mm; ET-2: 85 to 90 mm', is_required=1 WHERE template_id=346 AND sort_order=48; -- source_row 57
UPDATE div_trip_inspection_template_items SET section_name='Battery', item_no='ii', label_en='Check battery charger voltage & charging current.', label_hi='बैटरी चार्जर का वोल्टैज व चार्जिग करंट चैक करें', standard_value='110 V, 4 to 6 Amp.', is_required=1 WHERE template_id=346 AND sort_order=68; -- source_row 83
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='v', label_en='Check the oil accumulation in Oil Trap Chamber.', label_hi='ऑयल ट्रैप चैम्बर में तेल के जमाव की जांच करें।', standard_value='No accumulation', is_required=1 WHERE template_id=346 AND sort_order=77; -- source_row 93
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='i', label_en='Check condition of brake block and change if required. Adjust the piston stroke Check the gap between brake block & wheel in brake release condition 10mm & for WAG7 it should be 6mm).', label_hi='ब्रे्रेक ब्लाक को चेक करें, यदि आवश्यकता हो तब बदली करे। पिस्टन स्ट्रोक का समायोजन करें। लोको ब्रेक रिलीज स्थिति में पहिये से ब्रेक ब्लॉक के बीच का अंतराल 10 मिमी और WAG7 के लिए 6 मिमी होना चाहिए।', standard_value='Condemned brake block changed and brake piston stroke adjusted.', is_required=1 WHERE template_id=346 AND sort_order=95; -- source_row 117
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xi', label_en='Check CBC height of both ends.', label_hi='दोनों छोर की सीबीसी ऊंचाई की जांच करें।', standard_value='1030 mm to 1105 mm', is_required=1 WHERE template_id=346 AND sort_order=105; -- source_row 127
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xvi', label_en='Check intactness of connection strap bolts at all wheels Check Trunion position at all wheels Ensure clearance between connections to guide strip in WAP-1 & WAP-4 locos. Ensure no rubbing of connection strap with wheel of WAP-1 & WAP-4 locos at all wheels Check vertical & lateral play of hangers Check intactness of brake hanger top pin, split pin & safety sling. Check Trunion locking with split pin & proper oiling in WAP-1 & WAP-4 locos. Ensure safety sling for connection strap in WAP-1 & WAP-4 locos.', label_hi='डब्लुएपी 1, डब्लुएपी 4 की ब्रेक रिगिंग: सभी व्हील के कनेक्शन स्ट्रैप बोल्ट, ट्रुनियन स्थिति, गाइड स्ट्रिप क्लियरेंस, कनेक्शन स्ट्रैप रबिंग, हैंगर प्ले, ब्रेक हैंगर टॉप पिन, स्प्लिट पिन, सेफ्टी स्लिंग, ट्रुनियन लॉकिंग और ऑयलिंग की जाँच करें।', standard_value='Intact Intact Intact Intact Intact Intact Intact Intact', is_required=1 WHERE template_id=346 AND sort_order=110; -- source_row 132
UPDATE div_trip_inspection_template_items SET section_name='Fp Angle Cock And Hose Pipe', item_no='111', label_en='Check BP/FP angle cock operation, BP/FP flexible hoses and air leakage in both cabs.', label_hi='दोनो कैब में लगे बीपी तथा एफपी एंगल कॉक की ओपन तथा क्लोज पोजीशन में कार्य-जाँच करें। बीपी तथा एफपी फ्लेक्सीबल होस तथा एंगल कॉक में एयर लीकेज की जाँच करें। बीपी/एफपी होज़ पाइप में कोई डैमेज न हो, यह सुनिश्चित करें।', standard_value='Operation Normal', is_required=1 WHERE template_id=346 AND sort_order=111; -- source_row 134
UPDATE div_trip_inspection_template_items SET section_name='Under Frame Checking', item_no='ii', label_en='Check MSU bolts, gear case hex bolts and clamping bolts for availability and tightness.', label_hi='एमएसयू के बोल्ट, गियर केस हैक्सा बोल्ट और क्लॅपिंग बोल्ट उपलब्ध हैं तथा कसे हुए हैं, यह जांच करें।', standard_value='Intact', is_required=1 WHERE template_id=346 AND sort_order=122; -- source_row 146
UPDATE div_trip_inspection_template_items SET section_name='Ref:- Rdso Letter No. Rdso/2013/El/Ir/0159', item_no='Reference', label_en='Brake pressure reference table: BC pressure and application/release time', label_hi='ब्रेक प्रेशर संदर्भ तालिका: बीसी प्रेशर और एप्लीकेशन/रिलीज समय', standard_value='Reference row; no outcome required', is_required=0 WHERE template_id=346 AND sort_order=140; -- source_row 168
UPDATE div_trip_inspection_template_items SET section_name='Ref:- Rdso Letter No. Rdso/2013/El/Ir/0159', item_no='A-9 Goods', label_en='Brake via A-9 - C3W in Goods position', label_hi=NULL, standard_value='BC pressure: 1.8 kg/cm²', is_required=0 WHERE template_id=346 AND sort_order=141; -- source_row 169
UPDATE div_trip_inspection_template_items SET section_name='Ref:- Rdso Letter No. Rdso/2013/El/Ir/0159', item_no='A-9 Passenger', label_en='Brake via A-9 - C3W in Passenger position', label_hi=NULL, standard_value='BC pressure: 1.8 kg/cm²; application/release time as per source table', is_required=0 WHERE template_id=346 AND sort_order=142; -- source_row 171
UPDATE div_trip_inspection_template_items SET section_name='Ref:- Rdso Letter No. Rdso/2013/El/Ir/0159', item_no='SA-9 Reference', label_en='Brake via SA-9 - BC pressure reference', label_hi=NULL, standard_value='Reference row; no outcome required', is_required=0 WHERE template_id=346 AND sort_order=143; -- source_row 173
UPDATE div_trip_inspection_template_items SET section_name='Brake pressure checks', item_no='viii.', label_en='BP Pressure - Normal BP Pressure – On test plug (with BPSW pressed condition)', label_hi='बीपी प्रेशर – सामान्य बीपी प्रेशर – टेस्ट प्लग पर (BPSW दबाए जाने की स्थिति में)', standard_value='Pressure not to drop below prescribed limit', is_required=1 WHERE template_id=346 AND sort_order=144; -- source_row 175
UPDATE div_trip_inspection_template_items SET section_name='Brake pressure checks', item_no='ix.', label_en='FP Pressure - Normal FP Pressure – On test plug', label_hi='एफ़पी प्रेशर – सामान्य एफ़पी प्रेशर – टेस्ट प्लग पर', standard_value='Pressure not to drop below prescribed limit', is_required=1 WHERE template_id=346 AND sort_order=145; -- source_row 176
UPDATE div_trip_inspection_template_items SET section_name='Brake pressure checks', item_no='x', label_en='Apply loco brake & test loco on power, loco should not move 80% of continuous rating', label_hi='लोको में ब्रेक लगाकर ब्रेक पावर चेक करें। लोको 80% continuous rating पर नहीं हिलना चाहिए।', standard_value='Loco must not move at 80% continuous rating', is_required=1 WHERE template_id=346 AND sort_order=146; -- source_row 177
UPDATE div_trip_inspection_template_items SET section_name='General / जनरल', item_no='ii', label_en='Check DDS logging for one round trip.', label_hi='एक राउंड ट्रिप की DDS लॉगिंग की जांच करें।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=2; -- source_row 4
UPDATE div_trip_inspection_template_items SET section_name='Lights / लाइट्स', item_no='i', label_en='Clean the glass of headlight lamps and marker lights.', label_hi='हेड लाईट लॅम्‍प एवं मार्कर लाईट के कॉच साफ करें।', standard_value='Cleaned', is_required=1 WHERE template_id=347 AND sort_order=29; -- source_row 43
UPDATE div_trip_inspection_template_items SET section_name='Lights / लाइट्स', item_no='ii', label_en='Check operation of flasher light, marker light, headlight, cab light, desk light, and machine room light.', label_hi='फ्लेशर लाईट मार्करलाईट हेड लाईट कैब लाईट डीस्‍क लाईट मशीनरूम लाईट का ऑपरेशन चेक करें।', standard_value='Working Condition', is_required=1 WHERE template_id=347 AND sort_order=30; -- source_row 44
UPDATE div_trip_inspection_template_items SET section_name='Pantograph', item_no='i', label_en='inspect the entire upper structure of the pantograph assembly and check that the assembly horn, wear strip and support assembly have no cracks.', label_hi='पैन्‍टोग्राफ असेंबली के पूरे ऊपरी ढॉचे की विजुअल जॉच करें तथा जॉच करें कि असेम्‍बली हॉर्न, विअर स्‍ट्रीप तथा सपोर्ट असेम्‍बली में कोई क्रेक नहीं।', standard_value='No Crack', is_required=1 WHERE template_id=347 AND sort_order=32; -- source_row 49
UPDATE div_trip_inspection_template_items SET section_name='Pantograph', item_no='ix', label_en='Ensure PRV setting of HRPT Pantograph is within limit. Ref:- RDSO letter no. No. EL/2.2.1/High Reach/Faiveley)', label_hi='सुनिश्चित करें कि एचआरपीटी पैंटोग्राफ की पीआरवी सेटिंग सीमा के भीतर है।', standard_value='Within prescribed PRV setting limit', is_required=1 WHERE template_id=347 AND sort_order=40; -- source_row 57
UPDATE div_trip_inspection_template_items SET section_name='Roof Equipment', item_no='ii', label_en='Clean roof insulators and remove foreign material, if present.', label_hi='पेंटोग्राफ इंसुलेटर, हाई वोल्टेज बुशिंग इंसुलेटर, VCB सर्ज अरेस्टर, प्राइमरी वोल्टेज ट्रांसफॉर्मर इंसुलेटर, रूफ बार इंसुलेटर आदि को साफ करें तथा यदि तार, कपड़े के टुकड़े, पॉलिथीन आदि जैसे कोई बाहरी पदार्थ मौजूद हों तो उन्हें हटा दें।', standard_value='Cleaned', is_required=1 WHERE template_id=347 AND sort_order=43; -- source_row 61
UPDATE div_trip_inspection_template_items SET section_name='Draft Gear And Coupler', item_no='v', label_en='Measure CBC height of both ends.', label_hi='दोनों छोर की सीबीसी ऊंचाई मापें', standard_value='1030 mm to 1105 mm', is_required=1 WHERE template_id=347 AND sort_order=85; -- source_row 115
UPDATE div_trip_inspection_template_items SET section_name='Main Compressor', item_no='vi', label_en='check BP drop & Auto-flasher working', label_hi='RS वाल्व को संचालित करें और BP प्रेशर ड्रॉप तथा ऑटो-फ्लैशर की कार्यप्रणाली की जांच करें।', standard_value='Working properly', is_required=1 WHERE template_id=347 AND sort_order=125; -- source_row 165
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='Reference', label_en='Brake pressure reference table: Brake via A-9 full service/emergency by loco type', label_hi='ब्रेक प्रेशर संदर्भ तालिका: लोको प्रकार अनुसार A-9 फुल सर्विस/इमरजेंसी', standard_value='Reference row; no outcome required', is_required=0 WHERE template_id=347 AND sort_order=136; -- source_row 180
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='WAP-7', label_en='A-9 full service/emergency - WAP-7', label_hi=NULL, standard_value='BC pressure: 2.5 kg/cm²', is_required=0 WHERE template_id=347 AND sort_order=137; -- source_row 182
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='WAG-9', label_en='A-9 full service/emergency - WAG-9', label_hi=NULL, standard_value='BC pressure: 2.5 kg/cm²', is_required=0 WHERE template_id=347 AND sort_order=138; -- source_row 183
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='WAP-5', label_en='A-9 full service/emergency - WAP-5', label_hi=NULL, standard_value='BC pressure: 5.15 kg/cm²', is_required=0 WHERE template_id=347 AND sort_order=139; -- source_row 184
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='Reference', label_en='Brake pressure reference table: Brake via SA-9 full applied by loco type', label_hi='ब्रेक प्रेशर संदर्भ तालिका: लोको प्रकार अनुसार SA-9 फुल एप्लाइड', standard_value='Reference row; no outcome required', is_required=0 WHERE template_id=347 AND sort_order=140; -- source_row 185
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='WAP-7/WAG-9', label_en='SA-9 full applied - WAP-7/WAG-9', label_hi=NULL, standard_value='BC pressure: 3.5 kg/cm²', is_required=0 WHERE template_id=347 AND sort_order=141; -- source_row 186
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='WAP-5', label_en='SA-9 full applied - WAP-5', label_hi=NULL, standard_value='BC pressure: 5.15 kg/cm²', is_required=0 WHERE template_id=347 AND sort_order=142; -- source_row 187
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='viii', label_en='Apply A9 to full service, the BC pressure should not exceed 2.5kg/cm², Press PVEF, the loco brakes should be released. Apply A9 to emergency, BC pressure should be 2.5 kg/cm², press PVEF, the loco brakes remain in applied condition.', label_hi='लोको ब्रेक्स की संयोजन क्रिया की जांच करें: A9 को फुल सर्विस पोजीशन में लगाएं, BC प्रेशर 2.5 kg/cm² से अधिक नहीं होना चाहिए। PVEF दबाएं, लोको ब्रेक्स रिलीज हो जाने चाहिए। A9 को इमरजेंसी पोजीशन में लगाएं, BC प्रेशर 2.5 kg/cm² होना चाहिए। PVEF दबाएं, लोको ब्रेक्स लगे हुए ही रहने चाहिए।', standard_value='Intact', is_required=1 WHERE template_id=347 AND sort_order=145; -- source_row 191
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='xiv', label_en='Check the gap between brake block & wheel in brake release condition should be 10 mm). Ref:- RDSO’s SMI No.197-2001 Rev-1, Amendment dated 26/30-07-2001.', label_hi='पिस्टन स्ट्रोक समायोजित करें। WAP-7/WAG-9 में ब्रेक रिलीज स्थिति में ब्रेक ब्लॉक और व्हील के बीच का गैप 10 मिमी होना चाहिए; पिस्टन स्ट्रोक 107 से 117 मिमी।', standard_value='Condemned brake block changed and brake piston stroke adjusted.', is_required=1 WHERE template_id=347 AND sort_order=152; -- source_row 199
UPDATE div_trip_inspection_template_items SET section_name='Fp Angle Cock And Hose Pipe', item_no='i', label_en='Check BP/FP angle cock operation, BP/FP flexible hoses and air leakage in both cabs.', label_hi='दोनो कैब में लगे बीपी तथा एफपी एंगल कॉक की ओपन तथा क्लोज पोजीशन में कार्य-जाँच करें। बीपी तथा एफपी फ्लेक्सीबल होस तथा एंगल कॉक में एयर लीकेज की जाँच करें। बीपी/एफपी होज़ पाइप में कोई डैमेज न हो, यह सुनिश्चित करें।', standard_value='Operation Normal', is_required=1 WHERE template_id=347 AND sort_order=158; -- source_row 209
COMMIT;
