-- CSMT-PNVL UP HB coordinates (local + prod). Date: 2026-08-07.
-- Match: signal_number + section + direction, NULL-guarded. Source: data/CSMT_PNVL/ upload_lat_long_csmt_pnvl_up_hb.csv
-- Excludes RVJ S-3 (belongs to VDLR-GMN, not this section).

UPDATE div_signals SET latitude=18.99264, longitude=73.11891 WHERE signal_number='PNVL S-421' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.99256, longitude=73.11881 WHERE signal_number='PNVL S-422' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.99252, longitude=73.11868 WHERE signal_number='PNVL S-423' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.99524, longitude=73.11645 WHERE signal_number='PNVL S-425' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.99795, longitude=73.1138 WHERE signal_number='H-4714' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.00069, longitude=73.11093 WHERE signal_number='H-4704' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.00247, longitude=73.10772 WHERE signal_number='H-4614' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.00428, longitude=73.10439 WHERE signal_number='H-4608' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.00591, longitude=73.10119 WHERE signal_number='H-4600' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0067, longitude=73.09775 WHERE signal_number='H-4512' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.00761, longitude=73.09385 WHERE signal_number='H-4506' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.00868, longitude=73.08966 WHERE signal_number='H-4418' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0113, longitude=73.0858 WHERE signal_number='H-4406' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01432, longitude=73.08276 WHERE signal_number='H-4314' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01766, longitude=73.07935 WHERE signal_number='H-4306' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02043, longitude=73.07675 WHERE signal_number='H-4216' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02303, longitude=73.07418 WHERE signal_number='H-4210' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02616, longitude=73.07105 WHERE signal_number='H-4202' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02833, longitude=73.06821 WHERE signal_number='H-4116' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0286, longitude=73.06469 WHERE signal_number='H-4106' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02706, longitude=73.06146 WHERE signal_number='H-4014' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02512, longitude=73.05788 WHERE signal_number='H-4006' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02237, longitude=73.05249 WHERE signal_number='H-4000' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0216, longitude=73.0487 WHERE signal_number='H-3912' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02213, longitude=73.04517 WHERE signal_number='BEPR S-23' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0208, longitude=73.04188 WHERE signal_number='BEPR S-12' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01821, longitude=73.03794 WHERE signal_number='BEPR S-5' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01705, longitude=73.03509 WHERE signal_number='BEPR S-3' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01645, longitude=73.03094 WHERE signal_number='H-3706' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01626, longitude=73.02712 WHERE signal_number='H-3620' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02012, longitude=73.02124 WHERE signal_number='H-3602' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02319, longitude=73.01774 WHERE signal_number='H-3514' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02663, longitude=73.01648 WHERE signal_number='NEU S-42' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.03491, longitude=73.01826 WHERE signal_number='NEU S-23' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.03967, longitude=73.01857 WHERE signal_number='NEU S-5' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.04606, longitude=73.0188 WHERE signal_number='JNJ S-30' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.04998, longitude=73.01877 WHERE signal_number='JNJ S-29' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05354, longitude=73.01823 WHERE signal_number='JNJ S-20' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05725, longitude=73.01814 WHERE signal_number='JNJ S-21' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06142, longitude=73.01822 WHERE signal_number='H-3110' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06505, longitude=73.01677 WHERE signal_number='H-3018' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06641, longitude=73.0125 WHERE signal_number='H-3004' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06543, longitude=73.00821 WHERE signal_number='H-2936' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0646, longitude=73.00468 WHERE signal_number='VSH S-30' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0623, longitude=72.99772 WHERE signal_number='VSH S-23' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06075, longitude=72.9944 WHERE signal_number='VSH S-25' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0605, longitude=72.99066 WHERE signal_number='H-2804' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06197, longitude=72.98718 WHERE signal_number='H-2728' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06301, longitude=72.98356 WHERE signal_number='H-2710' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0624, longitude=72.97923 WHERE signal_number='H-2614' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06122, longitude=72.97416 WHERE signal_number='H-2604' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06017, longitude=72.96971 WHERE signal_number='H-2514' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05913, longitude=72.96528 WHERE signal_number='H-2504' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05794, longitude=72.96028 WHERE signal_number='H-2412' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05676, longitude=72.9557 WHERE signal_number='H-2404' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05564, longitude=72.95202 WHERE signal_number='H-2314' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05447, longitude=72.94827 WHERE signal_number='H-2306' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05317, longitude=72.94463 WHERE signal_number='H-2216' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05186, longitude=72.94099 WHERE signal_number='H-2212' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05065, longitude=72.9376 WHERE signal_number='MNKD S-30' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.04959, longitude=72.93414 WHERE signal_number='MNKD S-29' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.04776, longitude=72.93067 WHERE signal_number='MNKD S-22' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.04838, longitude=72.92766 WHERE signal_number='MNKD S-20' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0517, longitude=72.92082 WHERE signal_number='H-58' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05608, longitude=72.91386 WHERE signal_number='H-56' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05905, longitude=72.90887 WHERE signal_number='H-54' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06133, longitude=72.90384 WHERE signal_number='CMBR S-2' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06299, longitude=72.90027 WHERE signal_number='CMBR S-4' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06479, longitude=72.89395 WHERE signal_number='H-52' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06607, longitude=72.88869 WHERE signal_number='CLA S-28' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06721, longitude=72.88397 WHERE signal_number='CLA S-29' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.06417, longitude=72.87845 WHERE signal_number='CLA S-44' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05988, longitude=72.873 WHERE signal_number='CLA S-48' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05475, longitude=72.86966 WHERE signal_number='H-50' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.05004, longitude=72.86926 WHERE signal_number='H-48' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.04219, longitude=72.86796 WHERE signal_number='H-46' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.03686, longitude=72.86354 WHERE signal_number='H-44' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02923, longitude=72.86047 WHERE signal_number='RVJ S-24' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.02548, longitude=72.86087 WHERE signal_number='RVJ S-19' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01883, longitude=72.86087 WHERE signal_number='RVJ S-11' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01479, longitude=72.85805 WHERE signal_number='RVJ S-4' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.01177, longitude=72.85603 WHERE signal_number='H-38' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.00753, longitude=72.85522 WHERE signal_number='H-36' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=19.0023, longitude=72.85545 WHERE signal_number='H-34' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.99714, longitude=72.85388 WHERE signal_number='H-32' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.99391, longitude=72.85227 WHERE signal_number='H-30' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.9904, longitude=72.84841 WHERE signal_number='H-28' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.98823, longitude=72.84553 WHERE signal_number='H-26' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.98556, longitude=72.84285 WHERE signal_number='H-24' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.98073, longitude=72.8435 WHERE signal_number='H-20' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.97643, longitude=72.84456 WHERE signal_number='H-18' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.97276, longitude=72.84521 WHERE signal_number='H-16' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.96906, longitude=72.84447 WHERE signal_number='H-14' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.96518, longitude=72.84365 WHERE signal_number='H-12' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.96297, longitude=72.84152 WHERE signal_number='H-10' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.96063, longitude=72.83954 WHERE signal_number='H-08' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.95721, longitude=72.83851 WHERE signal_number='H-06' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.95392, longitude=72.8381 WHERE signal_number='H-04' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.95079, longitude=72.8382 WHERE signal_number='CSMT S-57' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.94816, longitude=72.83791 WHERE signal_number='CSMT S-53' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.94621, longitude=72.83641 WHERE signal_number='CSMT S-46' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);
UPDATE div_signals SET latitude=18.94469, longitude=72.83531 WHERE signal_number='CSMT S-23' AND section='CSMT-PNVL' AND direction='UP' AND (latitude IS NULL OR longitude IS NULL);

SELECT COUNT(*) total, SUM(latitude IS NOT NULL AND longitude IS NOT NULL) with_ll FROM div_signals WHERE is_active=1 AND section="CSMT-PNVL" AND line="UP HB" AND direction="UP";