-- Rename section headers to full corridor names: "<FROM>-<TO> <DIR> <DESIG> LINE"
-- (was just the line, e.g. "DN NE LINE" / "SNSI UP LINE"). FROM->TO ordered by direction.
-- Straightforward corridors only; the DIVA/BSR (DCC) complex block is deferred. Local + prod.
UPDATE div_signal_book_sections SET section_title = CASE section_code
  WHEN 'IGP_MMR_DN_NE'      THEN 'IGP-MMR DN NE LINE'
  WHEN 'IGP_MMR_UP_NE'      THEN 'MMR-IGP UP NE LINE'
  WHEN 'KSRA_IGP_DN_NE'     THEN 'KSRA-IGP DN NE LINE'
  WHEN 'KSRA_IGP_DN_NE_MID' THEN 'KSRA-IGP DN NE MIDDLE LINE'
  WHEN 'KSRA_IGP_UP_NE'     THEN 'IGP-KSRA UP NE LINE'
  WHEN 'KSRA_IGP_UP_NE_MID' THEN 'IGP-KSRA UP NE MIDDLE LINE'
  WHEN 'MMR_BSL_DN_NE'      THEN 'MMR-BSL DN NE LINE'
  WHEN 'MMR_BSL_UP_NE'      THEN 'BSL-MMR UP NE LINE'
  WHEN 'MMR_SNSI_SNSI_DN'   THEN 'MMR-SNSI DN SNSI LINE'
  WHEN 'MMR_SNSI_SNSI_UP'   THEN 'SNSI-MMR UP SNSI LINE'
  WHEN 'KJT_LNL_DN_SE'      THEN 'KJT-LNL DN SE LINE'
  WHEN 'KJT_LNL_DN_SE_MID'  THEN 'KJT-LNL DN SE MIDDLE LINE'
  WHEN 'KJT_LNL_UP_SE'      THEN 'LNL-KJT UP SE LINE'
  WHEN 'KJT_LNL_UP_SE_MID'  THEN 'LNL-KJT UP SE MIDDLE LINE'
  WHEN 'LNL_PUNE_DN_SE'     THEN 'LNL-PUNE DN SE LINE'
  WHEN 'LNL_PUNE_UP_SE'     THEN 'PUNE-LNL UP SE LINE'
  WHEN 'PNVL_KJT_DN_KJT'    THEN 'PNVL-KJT DN KJT LINE'
  WHEN 'PNVL_KJT_UP_KJT'    THEN 'KJT-PNVL UP KJT LINE'
  WHEN 'PNVL_JNPT_JNPT_DN'  THEN 'PNVL-JNPT DN JNPT LINE'
  WHEN 'PNVL_JNPT_JNPT_UP'  THEN 'JNPT-PNVL UP JNPT LINE'
  WHEN 'PNVL_ROHA_DN_KR'    THEN 'PNVL-ROHA DN KR LINE'
  WHEN 'PNVL_ROHA_UP_KR'    THEN 'ROHA-PNVL UP KR LINE'
  WHEN 'ROHA_RN_DN_KR'      THEN 'ROHA-RN DN KR LINE'
  WHEN 'ROHA_RN_UP_KR'      THEN 'RN-ROHA UP KR LINE'
  WHEN 'PEN_TVSG_DN_TVSG'   THEN 'PEN-TVSG DN TVSG LINE'
  WHEN 'PEN_TVSG_UP_TVSG'   THEN 'TVSG-PEN UP TVSG LINE'
  WHEN 'CLA_TMBY_DN_TMBY'   THEN 'CLA-TMBY DN TMBY LINE'
  WHEN 'CLA_TMBY_UP_TMBY'   THEN 'TMBY-CLA UP TMBY LINE'
  WHEN 'CLA_VDLR_BPT_DN'    THEN 'CLA-VDLR DN BPT LINE'
  WHEN 'CLA_VDLR_BPT_UP'    THEN 'VDLR-CLA UP BPT LINE'
  ELSE section_title END
WHERE section_code IN (
  'IGP_MMR_DN_NE','IGP_MMR_UP_NE','KSRA_IGP_DN_NE','KSRA_IGP_DN_NE_MID',
  'KSRA_IGP_UP_NE','KSRA_IGP_UP_NE_MID','MMR_BSL_DN_NE','MMR_BSL_UP_NE',
  'MMR_SNSI_SNSI_DN','MMR_SNSI_SNSI_UP','KJT_LNL_DN_SE','KJT_LNL_DN_SE_MID',
  'KJT_LNL_UP_SE','KJT_LNL_UP_SE_MID','LNL_PUNE_DN_SE','LNL_PUNE_UP_SE',
  'PNVL_KJT_DN_KJT','PNVL_KJT_UP_KJT','PNVL_JNPT_JNPT_DN','PNVL_JNPT_JNPT_UP',
  'PNVL_ROHA_DN_KR','PNVL_ROHA_UP_KR','ROHA_RN_DN_KR','ROHA_RN_UP_KR',
  'PEN_TVSG_DN_TVSG','PEN_TVSG_UP_TVSG','CLA_TMBY_DN_TMBY','CLA_TMBY_UP_TMBY',
  'CLA_VDLR_BPT_DN','CLA_VDLR_BPT_UP');
