-- Trip Shed VVH Step 3 display cleanup
-- Generated from reviewed catalog rows. Ambiguous source-owner review rows retain existing labels/standards except section headings.
START TRANSACTION;
UPDATE div_trip_inspection_template_items SET section_name='General / सामान्य', item_no='i', label_en='Check driver booking in log book; if any booking exists, inform shed via TLC.', label_hi='लॉग बुक में ड्रायवर बुकिंग चेक करें और यदि कोई बुकिंग है तो टीएलसी द्वारा शेड को सूचित करें।', standard_value='Checked', is_required=1 WHERE template_id=346 AND sort_order=1; -- source_row 3
UPDATE div_trip_inspection_template_items SET section_name='General / सामान्य', item_no='ii', label_en='Check Fault Messages Logged in FDCS and Take appropriate action. Check screen for proper working, any breakage or cracks.', label_hi='एफडीसीएस में दर्ज फॉल्ट संदेशों की जांच करें और उचित कार्रवाई करें। स्क्रीन के सही कार्य, किसी भी टूट-फूट या दरार की जाँच करें।', standard_value='Normal', is_required=1 WHERE template_id=346 AND sort_order=2; -- source_row 4
UPDATE div_trip_inspection_template_items SET section_name='Driver’S Desk', item_no='iii', label_en='Ensure emergency push button switch operates correctly.', label_hi='एमरजेंसी पुश बटन स्विंच की सही कार्य कर रहा है सुनिश्चित करें ।', standard_value='Working', is_required=1 WHERE template_id=346 AND sort_order=6; -- source_row 10
UPDATE div_trip_inspection_template_items SET section_name='Check The Availability Of Following Safety Items:', item_no='9', label_en='Fire extinguisher (4 Nos. each)', label_hi='अग्निशमन (कुल सं. - 4)', standard_value='Available', is_required=1 WHERE template_id=346 AND sort_order=9; -- source_row 14
UPDATE div_trip_inspection_template_items SET section_name='Check The Availability Of Following Safety Items:', item_no='10', label_en='LV Board (01No.)', label_hi='एल.वी. बोर्ड (कुल सं. - 1)', standard_value='Available', is_required=1 WHERE template_id=346 AND sort_order=10; -- source_row 15
UPDATE div_trip_inspection_template_items SET section_name='Check The Availability Of Following Safety Items:', item_no='11', label_en='Safety clamps (01 No.)', label_hi='सेेफ्टी कलैम्प (कुल सं. - 1)', standard_value='Available', is_required=1 WHERE template_id=346 AND sort_order=11; -- source_row 16
UPDATE div_trip_inspection_template_items SET section_name='Check The Availability Of Following Safety Items:', item_no='12', label_en='Spare BP & FP hose pipe (01 No. each)', label_hi='बीपी व एफपी पाइप (प्रत्येक-1)', standard_value='Available', is_required=1 WHERE template_id=346 AND sort_order=12; -- source_row 17
UPDATE div_trip_inspection_template_items SET section_name='Check The Availability Of Following Safety Items:', item_no='13', label_en='Screw coupling (01 No.)', label_hi='स्क्रु कपलिंग (कुल सं. - 1)', standard_value='Available', is_required=1 WHERE template_id=346 AND sort_order=13; -- source_row 18
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='i', label_en='Check all lighting, bulbs of cabs and corridors, cab fan if deficient or not working, attend accordingly.', label_hi='कैब और गलियारों की सभी लाइटें बल्ब तथा कैब फैन की जाँच करें। यदि कोई कमी हो या काम न कर रहा हो, तो आवश्यकतानुसार ठीक करें।', standard_value='Intact & is working condition.', is_required=1 WHERE template_id=346 AND sort_order=26; -- source_row 33
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='ii', label_en='Check working of flasher, tail and marker light and clean glasses.', label_hi='टेल लाईट, फ्लैशर लाईट व मार्कर लाईट को चैक करंे तथा उनके ग्लास को साफ करें ।', standard_value='In working condition.', is_required=1 WHERE template_id=346 AND sort_order=27; -- source_row 34
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='iii', label_en='Ensure working of both flasher lights on Auto/Manual position.', label_hi='फ्लैशर लाईट का आटो/मैन्युल स्थिति में कार्यरत होना सुनिश्चित करें ।', standard_value='In working condition.', is_required=1 WHERE template_id=346 AND sort_order=28; -- source_row 35
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='iv', label_en='Check the working of head light with DC-DC converter positions', label_hi='डीसी-डीसी कन्वर्टर की विभिन्न स्थितियों के साथ हेड लाइट के कार्य की जाँच करें। अ) मोड-1 ंद्धच्वेपजपवद.प् ब) मोड-2 इद्धच्वेपजपवद.प्प्', standard_value='Both position working normal', is_required=1 WHERE template_id=346 AND sort_order=29; -- source_row 36
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='v', label_en='Check the working of LV meter, Ammeter, CHBA Ammeter and Volt meter of loco.', label_hi='एल वी मीटर, अमीटर, सीएचबीए, अमीटर तथा वोल्टमीटर की जाॅच करें ।', standard_value='Working normal', is_required=1 WHERE template_id=346 AND sort_order=30; -- source_row 37
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='vi', label_en='Check working of all wipers, replace blade if required.', label_hi='सभी वाइपर के संचालन की जांच करें, आवश्यकता होने पर ब्लेड बदलें।', standard_value='Working normal', is_required=1 WHERE template_id=346 AND sort_order=31; -- source_row 38
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='vii', label_en='Check working of Horns (LV & HV)', label_hi='सभी हार्न को कार्यरत होना सुनिश्चित करें । (एलवी/एचवी)', standard_value='Working normal', is_required=1 WHERE template_id=346 AND sort_order=32; -- source_row 39
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='viii', label_en='Check the operation of BL board keys, ZPT, reverser keys & switches for slackness.', label_hi='बीएल, जेडपीटी त्था रिवर्सर की चाॅवी व स्विच की जाॅच करें । सुनिश्चित करें कि कोई स्विच स्लैक तो नहीं है ।', standard_value='Free operation', is_required=1 WHERE template_id=346 AND sort_order=33; -- source_row 40
UPDATE div_trip_inspection_template_items SET section_name='Lighting / लाईटिंग', item_no='ix', label_en='Check Hand brake & its operation.', label_hi='हैंड ब्रेक और उसके संचालन की जांच करें।', standard_value='Working normal', is_required=1 WHERE template_id=346 AND sort_order=34; -- source_row 41
UPDATE div_trip_inspection_template_items SET section_name='Ep Contactor & Relays', item_no='iv', label_en='check the condition of all movable and fixed contacts of reverser, CTF, C-118 for flashing.', label_hi='lHkh fjolZj] lh-Vh-,Q-lh&118 ds fQDl vkSj eqOgscy dkUVSDV ij QySf”kax dks दृष्टिगत रूप से tkWp djsa', standard_value='No flashing.', is_required=1 WHERE template_id=346 AND sort_order=54; -- source_row 65
UPDATE div_trip_inspection_template_items SET section_name='एस एम जी आर/आर जी आर/सी जी आर ैडळत्ध्त्ळत्ध्ब्ळत्', item_no='ii.', label_en='Check control air pressure of SMGR.', label_hi='एस एम जी आर के कंट्रोल प्रेशर की जाॅच करें', standard_value='3.5 किग्रा/सेमी2 3.5 kg/cm²्', is_required=1 WHERE template_id=346 AND sort_order=59; -- source_row 72
UPDATE div_trip_inspection_template_items SET section_name='Battery', item_no='iv', label_en='Record the battery voltage with switch HBA in “ON” condition (voltage should be 98 to 100V). If found battery voltage less, specific gravity to be check.', label_hi='HBA स्विच ‘ON’ स्थिति में रखते हुए बैटरी वोल्टेज रिकॉर्ड करें (वोल्टेज 98 से 100 V होना चाहिए)। यदि वोल्टेज कम पाया जाए, तो विशिष्ट गुरुत्व (specific gravity) की जांच करें।', standard_value='98-100 V', is_required=1 WHERE template_id=346 AND sort_order=70; -- source_row 85
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='i', label_en='Check the oil level in GR & transformer', label_hi='जीआर व ट्रान्सफार्मर में तेल स्तर की जाॅच करें ।', standard_value='GR above 20 deg Celsius Transformer above +15 deg Celsius', is_required=1 WHERE template_id=346 AND sort_order=73; -- source_row 89
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='ii', label_en='Check for oil leakage from GR, Transformer, Radiator & its bushing, oil pump and its vicinity.', label_hi='GR, ट्रांसफॉर्मर, रेडिएटर और उसके बुशिंग, तेल पंप एवं उसके आसपास के क्षेत्र से तेल रिसाव की जांच करें।', standard_value='No leakage', is_required=1 WHERE template_id=346 AND sort_order=74; -- source_row 90
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='iii', label_en='if it has turned Pink.', label_hi='सिलीका जेल यदि गुलाबी हो तो उसे बदल दें। त्मचसंबम ेपसपबं हमस', standard_value='Blue', is_required=1 WHERE template_id=346 AND sort_order=75; -- source_row 91
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='iv', label_en='Check the condition of power bushing for any flash, oil leakage and any abnormality.', label_hi='पवर बुशिंग में फ्लैशिंग, तेल रिसाव ओर अन्य असामान्यताओ की जाॅच करें', standard_value='No flashing & leakage.', is_required=1 WHERE template_id=346 AND sort_order=76; -- source_row 92
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='v', label_en='Check the oil accumulation in Oil Trap Chamber.', label_hi='ऑयल ट्रैप चैम्बर में तेल के जमाव की जांच करें।', standard_value='नहि है। छव', is_required=1 WHERE template_id=346 AND sort_order=77; -- source_row 93
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='vi', label_en='Check main transformer and its tank for cracks, breakage, or leaks.', label_hi='मुख्य ट्रांसफॉर्मर और उसका टैंक दरारों, टूट-फूट या रिसाव के लिए जांचें।', standard_value='No Damage', is_required=1 WHERE template_id=346 AND sort_order=78; -- source_row 94
UPDATE div_trip_inspection_template_items SET section_name='GR and TFP / जी आर और टी एफ पी', item_no='vii', label_en='Check A-33 bushing for any cracks, oil leakage & tightness of connection etc', label_hi='A-33 बुशिंग में किसी भी दरार, तेल रिसाव तथा कनेक्शन की कसावट आदि की जाँच करें।', standard_value='No leakage/No cracks', is_required=1 WHERE template_id=346 AND sort_order=79; -- source_row 95
UPDATE div_trip_inspection_template_items SET section_name='HOM, HOBA, ECC / एच ओ एम, एच ओबी ए, ई सी सी', item_no='i', label_en='Check the operation of HOM', label_hi='एच ओ एम के कार्य की जाच करें', standard_value='सामान्य ैउववजी', is_required=1 WHERE template_id=346 AND sort_order=80; -- source_row 97
UPDATE div_trip_inspection_template_items SET section_name='HOM, HOBA, ECC / एच ओ एम, एच ओबी ए, ई सी सी', item_no='ii', label_en='Check the position of HOBA, HQOP-1 & HQOP-2', label_hi='एच ओ बी अे, एच क्यु ओ पी-1 तथा एच क्यु ओ पी-2 की स्थिति को जाचें', standard_value='आॅन व्छ', is_required=1 WHERE template_id=346 AND sort_order=81; -- source_row 98
UPDATE div_trip_inspection_template_items SET section_name='HOM, HOBA, ECC / एच ओ एम, एच ओबी ए, ई सी सी', item_no='iii', label_en='Check ECC for proper operation, check with HRC fuse.', label_hi='ई सी सी की फ्युज लगाकर जाच करें', standard_value='Working.', is_required=1 WHERE template_id=346 AND sort_order=82; -- source_row 99
UPDATE div_trip_inspection_template_items SET section_name='HOM, HOBA, ECC / एच ओ एम, एच ओबी ए, ई सी सी', item_no='iv', label_en='Check the availability of spare fuses on tray, replace blown fuses (6A-05, 16A-03, 35A-2).', label_hi='स्पेयर फ्युज की उपलब्धता सुनिश्चित करें व खराब फ्युज बदली करें ।', standard_value='Spare fuse made available', is_required=1 WHERE template_id=346 AND sort_order=83; -- source_row 100
UPDATE div_trip_inspection_template_items SET section_name='Auxiliary Machines & Sl', item_no='ii', label_en='Clean MVRF wire mesh jali, remove polythene bags, paper etc.', label_hi='एसएल और एमवीआरएफ वायर मेष जाली को साफ करें पॉलिथीन बैग कागज आदि हटा दें।', standard_value='Cleaned', is_required=1 WHERE template_id=346 AND sort_order=85; -- source_row 103
UPDATE div_trip_inspection_template_items SET section_name='Traction Motors', item_no='v', label_en='Clean the TM net.', label_hi='टीएम नेट को साफ करें', standard_value='Cleaned', is_required=1 WHERE template_id=346 AND sort_order=91; -- source_row 110
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='i', label_en='Check condition of brake block and change if required.  Adjust the piston stroke Check the gap between brake block & wheel in brake release condition 10mm & for WAG7 it should be 6mm).', label_hi='ब्रे्रेक ब्लाक को चेक करें, यदि आवश्यकता होे तब बदली करे । पिस्टन सट्रोक का समायोजन करें) लोको ब्रेक रिलीज करे पहिये से ब्रेक ब्लाॅक के बिच का अंतराल जाॅंचे (10 मिमी अधिकतम) ॅ।ळध्7 (6 मिमी अधिकतम) ॅ।ळ5ए ॅ।ड4 दृ 95 जव 105 उउ ॅ।ळ7 दृ 107 जव 117उउ ॅ।च्1-4.68 जव 78 उउ ॅब्।ड3 दृ 105 जव 117 उउ ;', standard_value='Condemned brake block changed and brake piston stroke adjusted.', is_required=1 WHERE template_id=346 AND sort_order=95; -- source_row 117
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='ii', label_en='Ensure that there is no rubbing mark of brake blocks on wheel flange.', label_hi='सुनिश्चित करें कि ब्रेक ब्लॉक की कोई रबिंग मार्क व्हील फ्लैन्ज़ पर न हो।', standard_value='Normal', is_required=1 WHERE template_id=346 AND sort_order=96; -- source_row 118
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='iii', label_en='Check brake cylinder for proper operation, ensure no air leakage.', label_hi='ब्रेक सिलींडर के कार्य को जाॅंचे व सुनिश्चित करे कि हवा का रिसाब नही है ।', standard_value='No leakage, normal operation', is_required=1 WHERE template_id=346 AND sort_order=97; -- source_row 119
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='iv', label_en='Confirm brake pull rod and safety slings are intact.', label_hi='सुनिश्चित करे कि ब्रेक पुल राॅड व सेप्टी स्ंिलग ठीक है ।', standard_value='Intact', is_required=1 WHERE template_id=346 AND sort_order=98; -- source_row 120
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='v', label_en='Check TM bellows and its foundation bolts.', label_hi='टी एम के बेलो व उनके फाउडेंशन बोल्ट जाॅंचे ।', standard_value='Intact', is_required=1 WHERE template_id=346 AND sort_order=99; -- source_row 121
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='vi', label_en='Check all springs, compensating beams, equalizing beams, load pins and its cotter pins.', label_hi='सभी स्ंिप्रग, कंपेनसेटिंग बीम, इक्वलाइजिंग बीम, लोड पिन और इसकी कोटर पीन को चेक करे ।', standard_value='Intact', is_required=1 WHERE template_id=346 AND sort_order=100; -- source_row 122
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='vii', label_en='check the bogie frame, beams for any cracks etc.', label_hi='बेगी फ्रेम, बीम की जाॅच कर कि उसमें कोई दरार तो नही है ।', standard_value='Intact', is_required=1 WHERE template_id=346 AND sort_order=101; -- source_row 123
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='viii', label_en='Check cattle guard, rail guard, buffer foundation bolts, split pins etc for its intactness and tightness.', label_hi='कॅटल गार्ड, रेल गार्ड, बफर फाउंडेशन बोल्ट, स्पलिट पीन इ. ठीक से लगे हो व उनका कसाव जाॅचे', standard_value='Intact', is_required=1 WHERE template_id=346 AND sort_order=102; -- source_row 124
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='ix', label_en='Check the CBC screw coupling and its “D” shackle for proper functioning and lubricate it.', label_hi='सीबीसी स्क्रू कपलिंग और उसके डी” शैकल की उचित कार्यप्रणाली की जांच करें और उसे लुब्रिकेट करें।', standard_value='Normal', is_required=1 WHERE template_id=346 AND sort_order=103; -- source_row 125
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='x', label_en='Check any crack on CBC knukle and clevish & its proper operation from both cabs. Insert lock pin and checked CBC should not got open.', label_hi='सीबीसी पोर और क्लीविश पर किसी भी दरार की जाँच करें और सुनिश्चित करें कि सीबीसी लॉक पिन ठीक से लगा हुआ है।', standard_value='No crack & operation normal.', is_required=1 WHERE template_id=346 AND sort_order=104; -- source_row 126
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xi', label_en='Check CBC height of both ends.', label_hi='दोनों छोर की सीबीसी ऊंचाई की जांच करें।', standard_value='1030मिमी से 1105मिमी 1030उउ जव 1105उउ', is_required=1 WHERE template_id=346 AND sort_order=105; -- source_row 127
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xii', label_en='Check working of all sanders & condition of sand gear equipments.', label_hi='सँडर व्यवस्था सभी सैंडर्स के कार्य एवं सैंड गियर उपकरणों की स्थिति की जांच करें। ैंदक ळमंत मुनपचउमदजे', standard_value='Intact & Working', is_required=1 WHERE template_id=346 AND sort_order=106; -- source_row 128
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xiii', label_en='Intactness of Cover bolts. Provision of split pin-----', label_hi='एक्सल बाॅक्स ।गसम इवग कव्हर बोल्ट लगे है स्पलिट पिन लगी है एक्सल बाॅक्स टिल्ंिटग (डब्ल्यु अे पी 1 एवं 4 लोको', standard_value='Intact Available', is_required=1 WHERE template_id=346 AND sort_order=107; -- source_row 129
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xiv', label_en='Secondary Spring', label_hi='प्र्राइमरी स्ंिप्रग च्तपउंतल ैचतपदह सेकंडरी स्ंिप्रग', standard_value='Breakage/Shifting. Breakage/Shifting.', is_required=1 WHERE template_id=346 AND sort_order=108; -- source_row 130
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xv', label_en='Bolster of WAP-4 & WAP-1 locos. Friction piston pin', label_hi='डब्लुएपी 4, डब्लुएपी 1 लोको को बोल्टसर जाॅचे क्रॅक्र ब्तंबाण् फ्रिक्शन पिस्टन पिन लाइनर स्पदमत बतंबाण्', standard_value='Intact No crack', is_required=1 WHERE template_id=346 AND sort_order=109; -- source_row 131
UPDATE div_trip_inspection_template_items SET section_name='Mechanical / यांत्रिक', item_no='xvi', label_en='Check intactness of connection strap bolts at all wheels Check Trunion position at all wheels Ensure clearance between connections to guide strip in WAP-1 & WAP-4 locos. Ensure no rubbing of connection strap with wheel of WAP-1 & WAP-4 locos at all wheels Check vertical & lateral play of hangers Check intactness of brake hanger top pin, split pin & safety sling. Check Trunion locking with split pin & proper oiling in WAP-1 & WAP-4 locos. Ensure safety sling for connection strap in WAP-1 & WAP-4 locos.', label_hi='डब्लुएपी 1, डब्लुएपी 4 की ब्रेक रिगिंग क)   सभी व्हिल के कनेक्शन स्ट्रेप बोल्ट का लगा होना सुनिश्चित करे ख)  सभी व्हिल के ट्रा यूनियन की स्थिती की जाॅच करे घ)  डब्लुएपी 1, डब्लुएपी 4 लोको में गाइड स्ट्रिप तथा कनेक्शन के बीच में क्लिअरन्स सुनिश्चित करे । बद्ध ड)  डब्लुएपी 1, डब्लुएपी 4 लोको में सभी व्हिल के कनेक्शन स्ट्रिप का चक्को से ना धिसना सुनिश्चित करे । कद्ध च)  हैंगर में व्हर्टिकल व लेटरल प्ले चेक करे छ)  ब्रेक हॅंगर की टाॅप पिन, स्पलिट पिन, सेफ्टी स्ंिलग का लगे होने की जाॅच करें । ज)  डबलु एपी 1, डबलु एपी 4 लोको में ट्रायूनियन लाॅकिंग स्पलिट पिन व उचित आॅयलिंग की जाॅच करे । हद्ध ह)   डब्लु एपी 1, डब्लु एपी 4 लोको में कनेक्शन स्ट्रिप की सेफ्टी स्ंिलग का होना सुनिश्चित करें । ीद्ध ठतंाम त्पहहपदह व िॅ।च्.1 - ॅ।च्.4ण्', standard_value='Intact Intact Intact Intact Intact Intact Intact Intact', is_required=1 WHERE template_id=346 AND sort_order=110; -- source_row 132
UPDATE div_trip_inspection_template_items SET section_name='Fp Angle Cock And Hose Pipe', item_no='xx', label_en='In case of CRO, replace BP & FP hose pipes.', label_hi='CRO की स्थिति में BP एवं FP होज़ पाइप्स को बदलें।', standard_value='Checked', is_required=1 WHERE template_id=346 AND sort_order=114; -- source_row 137
UPDATE div_trip_inspection_template_items SET section_name='Under Frame Checking', item_no='x', label_en='Check oil leakage Ensure intactness of top and bottom bolt. Ensure tightness of all bolts. Check top and bottom boss crack in WAP-4 locos', label_hi='गिअर केस d- तेल रिसाव की जाँच करें। [k½ ऊपर और नीचे के बोल्ट की मजबूती सुनिश्चित करें। x½ सभी बोल्ट की कसावट सुनिश्चित करें। बण् घ) डब्लु एपी 4 लोको मेे टाॅप व बाॅटम बाॅस की कॅ्रकनेस की जाॅच करें कण् ळमंत बंेमे', standard_value='No leakage Intact Intact No cracks', is_required=1 WHERE template_id=346 AND sort_order=130; -- source_row 154
UPDATE div_trip_inspection_template_items SET section_name='Under Frame Checking', item_no='b', label_en='BP test plug', label_hi='बीपी टेस्ट प्लग', standard_value='AFL & Buzzer working and auto regression taking place.', is_required=1 WHERE template_id=346 AND sort_order=135; -- source_row 161
UPDATE div_trip_inspection_template_items SET section_name='Under Frame Checking', item_no='v', label_en='Check the blowing pressure of MR safety valve.', label_hi='एम आर सेफ्टी वाल्व के ब्लोइंग प्रेशर की जाच करें', standard_value='10.5 किग्रा/सेमी2 10.5 kg/cm²', is_required=1 WHERE template_id=346 AND sort_order=139; -- source_row 166
UPDATE div_trip_inspection_template_items SET section_name='General / जनरल', item_no='i', label_en='Check driver booking in log book; if any booking exists, inform shed via TLC.', label_hi='लॉग बुक में ड्रायवर बुकिंग चेक करें और यदि कोई बुकिंग है तो टीएलसी द्वारा शेड को सूचित करें।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=1; -- source_row 3
UPDATE div_trip_inspection_template_items SET section_name='General / जनरल', item_no='ii', label_en='check.', label_hi='एक राउंड ट्रिप की DDS लॉगिंग की जांच करें। क्क्ै सवहहपदहे वित वदम तवनदक जतपच जव इम', standard_value='चेक किया ब्ीमबामक', is_required=1 WHERE template_id=347 AND sort_order=2; -- source_row 4
UPDATE div_trip_inspection_template_items SET section_name='General / जनरल', item_no='iii', label_en='Check that there is no damage to the loco body structure.', label_hi='लोको बॉडी स्‍ट्रक्‍चर में कोई डेंमेज नहीं है यह चेक करें।', standard_value='No damage', is_required=1 WHERE template_id=347 AND sort_order=3; -- source_row 5
UPDATE div_trip_inspection_template_items SET section_name='Driver’S Desk', item_no='i', label_en='Ensure transparent rubber caps on push buttons in driver’s cab.', label_hi='ड्रायव्‍हर कैब में लगी पुश बंटन पर लगे ट्रान्‍सपरंट रबर कैप का होना सुनिश्चित करें।', standard_value='Fitted', is_required=1 WHERE template_id=347 AND sort_order=8; -- source_row 13
UPDATE div_trip_inspection_template_items SET section_name='Driver’S Desk', item_no='iv', label_en='Ensure emergency push button switch operates correctly.', label_hi='एमरजेंसी पुश बटन स्विंच की सही कार्य कर रहा है सुनिश्चित करें ।', standard_value='Working', is_required=1 WHERE template_id=347 AND sort_order=11; -- source_row 16
UPDATE div_trip_inspection_template_items SET section_name='स्‍पीडोमीटर ैच्म्म्क्व्डम्ज्म्त्', item_no='i', label_en='Note down Date, time, KM Earned and status of memory. Check display light & intactness of all connection.', label_hi='तिथि, समय, अर्जित किलोमीटर एवं मेमोरी की स्थिति नोट करें। डिस्प्ले लाइट एवं सभी कनेक्शनों की सुदृढ़ता की जांच करें।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=14; -- source_row 21
UPDATE div_trip_inspection_template_items SET section_name='Doors And Footsteps', item_no='i', label_en='Check the operation of external door locks, Machine room door & its locks and inspect for any damage & attend accordingly.', label_hi='दरवाजे के बाहरी ताले, मशीन रूम का दरवाज़ा और उसके ताले के कार्य की जॉच करें तथा कोई डॅमेज है या नही देखे एवं अनुसार कार्यवाही करें ।', standard_value='Working', is_required=1 WHERE template_id=347 AND sort_order=21; -- source_row 30
UPDATE div_trip_inspection_template_items SET section_name='Look Out Glass And Side Window', item_no='i', label_en='Clean the lookout glass with detergent/water. Clean dust and debris from sliding window glass.', label_hi='लुकआउट ग्लास को डिटर्जेंट/पानी से साफ करें। स्लाइडिंग विंडो ग्लास से धूल एवं मलबा साफ करें।', standard_value='Cleaned', is_required=1 WHERE template_id=347 AND sort_order=23; -- source_row 33
UPDATE div_trip_inspection_template_items SET section_name='Simulation Mode', item_no='31', label_en='Check the working of the following: No Air leakage from VCB and SR contactors. Working of TE/BE up to Full traction and braking operation. Dropping of TE/BE through RS & A-9. Working of VCD through BPVG, foot switch, BPVR and application of penalty brakes from both cabs.', label_hi='निम्नलिखित की कार्य स्थिति की जांच करें: a) VCB एवं SR कॉन्टैक्टर्स से किसी भी प्रकार का एयर लीकेज न हो।b) पूर्ण ट्रैक्शन एवं ब्रेकिंग ऑपरेशन तक TE/BE का सही तरीके से कार्य करना।c) RS एवं A-9 के माध्यम से TE/BE का ड्रॉप होना।d) BPVG, फुट स्विच, BPVR के माध्यम से VCD का कार्य करना तथा दोनों कैब से पेनाल्टी ब्रेक का लगना।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=31; -- source_row 46
UPDATE div_trip_inspection_template_items SET section_name='Pantograph', item_no='vi', label_en='check for any cracks.', label_hi='फुट माऊंटिग इंसुलेटर को साफ करें और चेक करे कि कोई क्रेक तो नहीं है । ब्समंद विवज उवनदजपदह पदेनसंजवत ंदक', standard_value='Clean/No crack', is_required=1 WHERE template_id=347 AND sort_order=37; -- source_row 54
UPDATE div_trip_inspection_template_items SET section_name='Pantograph', item_no='viii', label_en='Check upper thrust of both the pantograph. IR03- On 7.0Kgf, Panto pan should not leave OHE while on 7.5Kgf, panto pan should leave OHE by a paper gap between OHE & Panto pan. HRPT- After putting 7.0Kgf, pull the panto pan towards lower side, it must be stop wherever pulling force removed. Similarly, during application of upper force, Panto pan should stop wherever upper force removed.', label_hi='दोनों पेंटोग्राफ के ऊपरी थ्रस्ट की जाँच करें। दोनों पैंटोग्राफ की अपर थ्रस्ट की जांच करें।IR03 - 7.0 किलोग्राम-फोर्स (Kgf) पर पैंटो पैन को ओएचई (OHE) से अलग नहीं होना चाहिए, जबकि 7.5 किलोग्राम-फोर्स (Kgf) पर पैंटो पैन और ओएचई के बीच कागज़ की मोटाई जितना अंतर आ जाना चाहिए।HRPT - 7.0 किलोग्राम-फोर्स (Kgf) लगाने के बाद पैंटो पैन को नीचे की ओर खींचें, खींचने की ताकत हटते ही पैंटो पैन को वहीं रुक जाना चाहिए। इसी प्रकार, जब ऊपर की ओर बल लगाया जाए, तो बल हटते ही पैंटो पैन को वहीं रुक जाना चाहिए।', standard_value='7.0 किलोग्राम 7.0 kgf', is_required=1 WHERE template_id=347 AND sort_order=39; -- source_row 56
UPDATE div_trip_inspection_template_items SET section_name='Main Transformer', item_no='i', label_en='Check the oil level indicator on the both conservators of Transformer and ensure there is no leakage. Ensure Oil level of both conservator of TFP should be between min and max level.', label_hi='ट्रांसफॉर्मर के दोनों कंजरवेटर पर तेल स्तर संकेतक की जांच करें और सुनिश्चित करें कि कोई रिसाव न हो। TFP के दोनों कंजरवेटर का तेल स्तर न्यूनतम और अधिकतम स्तर के बीच होना चाहिए।', standard_value='No Leakage/ level Between min and max', is_required=1 WHERE template_id=347 AND sort_order=46; -- source_row 65
UPDATE div_trip_inspection_template_items SET section_name='Main Transformer', item_no='v', label_en='if it has turned Pink.', label_hi='सिलीका जेल यदि गुलाबी हो तो उसे बदल दें। त्मचसंबम ेपसपबं हमस', standard_value='Blue', is_required=1 WHERE template_id=347 AND sort_order=50; -- source_row 69
UPDATE div_trip_inspection_template_items SET section_name='Traction Converter', item_no='i', label_en='Check the coolant level indicator on the both convertors and ensure there is no leakage. Ensure coolant level of both convertors should be between min and max level.', label_hi='दोनों कन्वर्टर पर कूलेंट स्तर संकेतक की जांच करें और सुनिश्चित करें कि कोई रिसाव न हो। दोनों कन्वर्टर का कूलेंट स्तर न्यूनतम और अधिकतम स्तर के बीच होना चाहिए।', standard_value='No Leakage/ level Between min and max', is_required=1 WHERE template_id=347 AND sort_order=52; -- source_row 72
UPDATE div_trip_inspection_template_items SET section_name='Traction Converter', item_no='iii', label_en='Check for loose or missing body cover screws and repair as needed.', label_hi='कवर की लूज या निकल हुए स्‍कू की जॉच करें यदि जरूरत हो तो सुधारे।', standard_value='No Leakage', is_required=1 WHERE template_id=347 AND sort_order=54; -- source_row 74
UPDATE div_trip_inspection_template_items SET section_name='Traction Converter', item_no='v', label_en='check for external damage & oil leakage from OCB radiator.', label_hi='OCB रेडिएटर में किसी भी बाहरी क्षति एवं तेल रिसाव की दृश्य जांच करें।', standard_value='No Leakage', is_required=1 WHERE template_id=347 AND sort_order=56; -- source_row 76
UPDATE div_trip_inspection_template_items SET section_name='Hotel Load', item_no='iii', label_en='Check all fault messages logged in the HLC/Log book and take appropriate action.', label_hi='HLC/लॉग बुक में दर्ज सभी दोषसंदेशों (fault messages) की जाँच करें और तदनुसार उचित कार्रवाई करें।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=69; -- source_row 93
UPDATE div_trip_inspection_template_items SET section_name='Battery', item_no='i', label_en='inspect the battery box for any external damage, its hanging support & condition of battery cables.', label_hi='बैटरी बॉक्स की किसी भी बाहरी क्षति, उसके हैंगिंग सपोर्ट एवं बैटरी केबलों की स्थिति की दृश्य जांच करें।', standard_value='Intact', is_required=1 WHERE template_id=347 AND sort_order=74; -- source_row 101
UPDATE div_trip_inspection_template_items SET section_name='Battery', item_no='ii', label_en='apply petroleum jelly if found dry.', label_hi='बैटरी सेल के टर्मिनल को साफ करें, यदि सूखा पाया जाए तो पेट्रोलियम जेली लगाएँ। ब्समंद जीम जमतउपदंस व िइंजजमतल बमससए', standard_value='Cleaned', is_required=1 WHERE template_id=347 AND sort_order=75; -- source_row 102
UPDATE div_trip_inspection_template_items SET section_name='Battery', item_no='iv', label_en='Record the battery voltage with switch 112.1 in “ON” at SB-2 panel in machine room (voltage should be 95 to 105V).', label_hi='मशीन रूम में SB-2 पैनल पर स्विच 112.1 को “ON” स्थिति में रखकर बैटरी वोल्टेज रिकॉर्ड करें (वोल्टेज 95 से 105V के बीच होना चाहिए)।', standard_value='95-105 V', is_required=1 WHERE template_id=347 AND sort_order=77; -- source_row 104
UPDATE div_trip_inspection_template_items SET section_name='Battery', item_no='vi', label_en='Record the CHBA voltage.', label_hi='CHBA वोल्टेज रिकॉर्ड करें।', standard_value='110 V', is_required=1 WHERE template_id=347 AND sort_order=79; -- source_row 106
UPDATE div_trip_inspection_template_items SET section_name='Battery', item_no='vii', label_en='Check the function of MCPA with BL switch in “D” Mode.', label_hi='BL स्विच को “D” मोड में रखकर MCPA के फंक्शन की जांच करें।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=80; -- source_row 107
UPDATE div_trip_inspection_template_items SET section_name='Draft Gear And Coupler', item_no='iv', label_en='inspect the CBC striker casting assembly.', label_hi='सी.बी.सी.स्‍ट्राइकर कॉस्‍टींग एसेंम्‍ब्‍ली व्हिजुयली चेंक करें।', standard_value='Working', is_required=1 WHERE template_id=347 AND sort_order=84; -- source_row 114
UPDATE div_trip_inspection_template_items SET section_name='Suspension / सस्पेंशन', item_no='i', label_en='Check for cracks or damage in primary and secondary helical springs in between Bogie-Body & in between Axle box-Bogie.', label_hi='बोगी-बॉडी के बीच एवं एक्सल बॉक्स-बोगी के बीच में प्राथमिक और द्वितीयक हेलिकल स्प्रिंग्स में दरार या क्षति की जांच करें।', standard_value='No Crack/ No Damage', is_required=1 WHERE template_id=347 AND sort_order=91; -- source_row 124
UPDATE div_trip_inspection_template_items SET section_name='Suspension / सस्पेंशन', item_no='ii', label_en='Check oil leakage and condition of nut bolt of all dampers.', label_hi='सभी डॅम्‍परो का ऑइल लिंकेज तथा नट बोल्‍ट की स्थिति की जांच करें।', standard_value='No Leakage/ Normal', is_required=1 WHERE template_id=347 AND sort_order=92; -- source_row 125
UPDATE div_trip_inspection_template_items SET section_name='Suspension / सस्पेंशन', item_no='iii', label_en='Inspect spheribloc of axle guide links on wheels 1 to 12 for cracks. Crack in spheriblocs should not be more than 270 Degrees', label_hi='एक्‍सल गार्डड लिंक की स्‍फेरीब्‍लाकों की स्थिति जॉच करें व्‍हील न.1 से 12 तक सभी स्‍फेरीब्‍लॉक चैक करें कि क्रेक नहीं हैं | स्फेरिब्लॉक में क्रैक 270 डिग्री से अधिक नहीं होना चाहिए।', standard_value='No Crack', is_required=1 WHERE template_id=347 AND sort_order=93; -- source_row 126
UPDATE div_trip_inspection_template_items SET section_name='Bogie Frame And Brake Gear', item_no='ii', label_en='Inspect bogie frame and damper base for cracks or damage.', label_hi='बोगी फ्रेम एवं या डॅम्‍पर बेस का क्रॅक अथवा डेंमेज के लिए निरीक्षण करें।', standard_value='No Crack', is_required=1 WHERE template_id=347 AND sort_order=95; -- source_row 129
UPDATE div_trip_inspection_template_items SET section_name='Bogie Frame And Brake Gear', item_no='iv', label_en='Check earthing shunt fitted in between bogie and body.', label_hi='बोगी और बॉडी के बीच फिट किया गया अर्थिंग शंट जांचें।', standard_value='100 प्रतिशत 100%', is_required=1 WHERE template_id=347 AND sort_order=97; -- source_row 131
UPDATE div_trip_inspection_template_items SET section_name='Bogie Frame And Brake Gear', item_no='vi', label_en='Check correct position of bogie-I and bogie-II, isolation cock.', label_hi='बोगी। तथा बोगी-।। आयसोलेशन कॉक सही स्थिति में होने की जॉच करें।', standard_value='Open', is_required=1 WHERE template_id=347 AND sort_order=99; -- source_row 133
UPDATE div_trip_inspection_template_items SET section_name='Gear Case', item_no='ii', label_en='Check oil level from gear case spy glass; add oil if needed. Verify drain plug fitting, tightness and sealing.', label_hi='गियर केस के स्पाई ग्लास से ऑइल लेवल की जॉच करें तथा जरूरत हो तो ऑईल डाले ड्रेन प्‍लग का सही तरह से लगा होना और उसकी टाईटनेस तथा सिलिंग चेक करें।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=117; -- source_row 155
UPDATE div_trip_inspection_template_items SET section_name='Main Compressor', item_no='ii', label_en='check pipes and support clamps for condition and leakage. Ensure protection guards on compressor are intact & safety slings are fitted on both compressors. Also, visually check compressor fan blades.', label_hi='पाइप्स और सपोर्ट क्लैम्प्स की स्थिति एवं लीकेज की दृश्य जांच करें। सुनिश्चित करें कि कंप्रेसर पर लगे प्रोटेक्शन गार्ड सुरक्षित हैं और दोनों कंप्रेसरों पर सेफ्टी स्लिंग्स लगे हुए हैं। साथ ही, कंप्रेसर के फैन ब्लेड्स की भी दृश्य जांच करें।', standard_value='No Damage/ No Leakage', is_required=1 WHERE template_id=347 AND sort_order=121; -- source_row 161
UPDATE div_trip_inspection_template_items SET section_name='Auxiliary Compressor', item_no='iv', label_en='Drain the Moisture from Auxiliary Compressor.', label_hi='ऑक्‍झीलीयरी कंप्रेसर से मॉइश्चर को ड्रेन करें।', standard_value='ड्रेन किया /Drained', is_required=1 WHERE template_id=347 AND sort_order=129; -- source_row 170
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='i', label_en='Check operation of A-9 & SA-9 brakes.', label_hi='A-9 एवं SA-9 ब्रेक के संचालन की जांच करें।', standard_value='Working properly', is_required=1 WHERE template_id=347 AND sort_order=133; -- source_row 177
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='ii', label_en='Check free movement of brake controller.', label_hi='ब्रेक कंट्रोलर की फ्री मूवमेंट चेक करें।', standard_value='Working properly', is_required=1 WHERE template_id=347 AND sort_order=134; -- source_row 178
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='iii', label_en='Apply and release brakes repeatedly from both cabs and ensure BP, BC pressure build-up and drop correctly.', label_hi='दोनों केब से ब्रेक को बार-बार लगाकर और छोड़कर जांचें, और सुनिश्चित करें कि BP एवं BC प्रेशर सही तरीके से बढ़ और घट रहे हैं।', standard_value='Working properly', is_required=1 WHERE template_id=347 AND sort_order=135; -- source_row 179
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='iv', label_en='Loco Type', label_hi='लोको प्रकार', standard_value='Brake via A-9 Full Service/ Emergency', is_required=1 WHERE template_id=347 AND sort_order=136; -- source_row 180
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='137', label_en='ॅ।च्.7', label_hi=NULL, standard_value='2ण्5 ज्ञहध्बउ2', is_required=1 WHERE template_id=347 AND sort_order=137; -- source_row 182
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='138', label_en='ॅ।ळ.9', label_hi=NULL, standard_value='2ण्5 ज्ञहध्बउ2', is_required=1 WHERE template_id=347 AND sort_order=138; -- source_row 183
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='139', label_en='ॅ।च्.5', label_hi=NULL, standard_value='5ण्15 ज्ञहध्बउ2', is_required=1 WHERE template_id=347 AND sort_order=139; -- source_row 184
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='v', label_en='Loco Type', label_hi='लोको प्रकार', standard_value='Brake via SA-9 Full Applied', is_required=1 WHERE template_id=347 AND sort_order=140; -- source_row 185
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='141', label_en='ॅ।च्.7ध्ॅ।ळ.9', label_hi=NULL, standard_value='3ण्5 ज्ञहध्बउ2', is_required=1 WHERE template_id=347 AND sort_order=141; -- source_row 186
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='142', label_en='ॅ।च्.5', label_hi=NULL, standard_value='5ण्15 ज्ञहध्बउ2', is_required=1 WHERE template_id=347 AND sort_order=142; -- source_row 187
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='vi', label_en='BP Pressure - Normal BP Pressure – On test plug Ref:- RDSO’s TECHNICAL CIRCULAR NO. RDSO/2012/EL/TC/0113, Rev.''0'', Dated 29.03.2012.', label_hi='बीपी प्रेशर – सामान्य बीपी प्रेशर – टेस्ट प्लग पर', standard_value='Pressure not to drop below 4.0 kg/cm2 on 7.5mm hole T/P in 01 min.', is_required=1 WHERE template_id=347 AND sort_order=143; -- source_row 189
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='vii', label_en='FP Pressure - Normal FP Pressure – On test plug Ref:- RDSO’s TECHNICAL CIRCULAR NO. RDSO/2012/EL/TC/0113, Rev.''0'', Dated 29.03.2012.', label_hi='एफ़पी प्रेशर – सामान्य एफ़पी प्रेशर – टेस्ट प्लग पर', standard_value='Pressure not to drop below 5.5 kg/cm2 on 5 mm hole T/P in 01 min.', is_required=1 WHERE template_id=347 AND sort_order=144; -- source_row 190
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='viii', label_en='Apply A9 to full service, the BC pressure should not exceed 2.5kg/cm², Press PVEF, the loco brakes should be released. Apply A9 to emergency, BC pressure should be 2.5 kg/cm², press PVEF, the loco brakes remain in applied condition.', label_hi='लोको ब्रेक्स की संयोजन क्रिया की जांच करें: a) A9 को फुल सर्विस पोजीशन में लगाएं, BC प्रेशर 2.5 kg/cm² से अधिक नहीं होना चाहिए। PVEF दबाएं, लोको ब्रेक्स रिलीज हो जाने चाहिए। b) A9 को इमरजेंसी पोजीशन में लगाएं, BC प्रेशर 2.5 kg/cm² होना चाहिए। PVEF दबाएं, लोको ब्रेक्स लगे हुए ही रहने चाहिए। ंद्ध इद्ध ब्वदरनदबजपवद ूवतापदह व िसवबव इतंामेरू', standard_value='Intact', is_required=1 WHERE template_id=347 AND sort_order=145; -- source_row 191
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='a', label_en='RS valve in emergency position', label_hi='आर एस वाल्व एमरजेंसी स्थिति में', standard_value='AFL & Buzzer working', is_required=1 WHERE template_id=347 AND sort_order=146; -- source_row 193
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='b', label_en='BP test plug', label_hi='बीपी टेस्ट प्लग', standard_value='AFL & Buzzer working', is_required=1 WHERE template_id=347 AND sort_order=147; -- source_row 194
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='x', label_en='Check MR pressure cut in & cut out from 8.0Kg/cm2 to 9.0Kg/cm2 Ref:- RDSO’s TECHNICAL CIRCULAR NO. RDSO/2012/EL/TC/0113, Rev.''0'', Dated 29.03.2012.', label_hi='MR प्रेशर का कट.इन एवं कट.आउट 8.0 Kg/cm² से 9.0 Kg/cm² तक जांचें।', standard_value='अधिकतम 30 सेकंड Max 30sec', is_required=1 WHERE template_id=347 AND sort_order=148; -- source_row 195
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='xi', label_en='Check the blowing pressure of MR safety valve.', label_hi='एम आर सेफ्टी वाल्व के ब्लोइंग प्रेशर की जाच करें', standard_value='10.5 किग्रा/सेमी2 10.5 kg/cm²', is_required=1 WHERE template_id=347 AND sort_order=149; -- source_row 196
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='xii', label_en='Check temperature of MSU Bearings & TM Bearings (CE & PE) & Axle Bearings.', label_hi='एक्सल बेरिंग, एम.एस.यु. बीअरिंग और टीएम बीअरिंग (सीई व पी ई) के तापमान की जाॅच करें', standard_value='परिवेश के तापमान +27oC से अिध्ाक नही। Not more than ambient temp +27oC.', is_required=1 WHERE template_id=347 AND sort_order=150; -- source_row 197
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='xiii', label_en='Apply loco brake & test loco on power, loco should not move up to 150 KN', label_hi='लोेको में ब्रेक लगाकर ब्रेक पावर चेक करें । लोकों 150 KN पर नही हिलना चाहिए', standard_value='Not moved / स्थानांतरित नहीं हुआ', is_required=1 WHERE template_id=347 AND sort_order=151; -- source_row 198
UPDATE div_trip_inspection_template_items SET section_name='A-9, SA-9 and RS Valve / A-9, SA-9 और RS वाल्व', item_no='xiv', label_en='Check the gap between brake block & wheel in brake release condition should be 10 mm). Ref:- RDSO’s SMI No.197-2001 Rev-1, Amendment dated 26/30-07-2001.', label_hi='पिस्टन स्ट्रोक समायोजित करें WAP-7/WAG-9 – 107 से 117 मिमी (ब्रेक रिलीज स्थिति में ब्रेक ब्लॉक और व्हील के बीच का गैप 10 मिमी होना चाहिए)। ।करनेज जीम चपेजवद ेजतवाम ॅ।च्7ध्ॅ।ळ9 दृ 107 जव 117उउ ;', standard_value='Condemned brake block changed and brake piston stroke adjusted.', is_required=1 WHERE template_id=347 AND sort_order=152; -- source_row 199
UPDATE div_trip_inspection_template_items SET section_name='Pneumatic Panel', item_no='i', label_en='inspect the pneumatic panel for any air leakage.', label_hi='वायु रिसाव के लिए न्यूमैटिक पैनल का दृश्यात्मक निरीक्षण करें।', standard_value='No Leakage', is_required=1 WHERE template_id=347 AND sort_order=153; -- source_row 201
UPDATE div_trip_inspection_template_items SET section_name='Fp Angle Cock And Hose Pipe', item_no='iv', label_en='In case of CRO, replace BP & FP hose pipes.', label_hi='CRO की स्थिति में BP एवं FP होज़ पाइप्स को बदलें।', standard_value='Checked', is_required=1 WHERE template_id=347 AND sort_order=161; -- source_row 212
COMMIT;
