-- Add 9 missed repeater signals, each inserted just before its parent (parent row - 5)
-- in CSMT_PNVL_DN_HB / CSMT_PNVL_UP_HB / CSMT_KYN_DN_TH. Additive; local then prod.
-- Re-run magnet backfill after (magnet_id starts NULL).

INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('H-09 REP', 'H09REP', NULL, NULL, 'CSMT-PNVL', 'DN HB', 'DN', 'SNRD PF', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('H-13 REP', 'H13REP', NULL, NULL, 'CSMT-PNVL', 'DN HB', 'DN', 'DKRD PF', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('H-23 REP', 'H23REP', NULL, NULL, 'CSMT-PNVL', 'DN HB', 'DN', 'CTGN PF', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('MNKD S-4 REP', 'MNKDS4REP', 'MNKD', 'Mankhurd', 'CSMT-PNVL', 'DN HB', 'DN', 'MNKD PF', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('VSH S-5 REP', 'VSHS5REP', 'VSH', 'Vashi', 'CSMT-PNVL', 'DN HB', 'DN', 'VSH PF', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('MNKD S-22 REP', 'MNKDS22REP', 'MNKD', 'Mankhurd', 'CSMT-PNVL', 'UP HB', 'UP', 'MNKD PF', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('K-035 REP', 'K035REP', NULL, NULL, 'CSMT-KYN', 'DN TH', 'DN', 'ON GC PF-3', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('VK S-5 REP', 'VKS5REP', 'VK', 'Vikhroli', 'CSMT-KYN', 'DN TH', 'DN', 'ON VK PF-3', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, is_active) VALUES ('K-4001 REP', 'K4001REP', NULL, NULL, 'CSMT-KYN', 'DN TH', 'DN', 'ON MBQ PF-3', 'Repeater', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 0, 0, 0, 1);

-- book rows: repeater just before its parent
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 595, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='H-09 REP' AND section='CSMT-PNVL' AND line='DN HB'), 'H-09 REP', 'SNRD PF', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_PNVL_DN_HB';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 795, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='H-13 REP' AND section='CSMT-PNVL' AND line='DN HB'), 'H-13 REP', 'DKRD PF', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_PNVL_DN_HB';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 1295, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='H-23 REP' AND section='CSMT-PNVL' AND line='DN HB'), 'H-23 REP', 'CTGN PF', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_PNVL_DN_HB';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 4395, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='MNKD S-4 REP' AND section='CSMT-PNVL' AND line='DN HB'), 'MNKD S-4 REP', 'MNKD PF', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_PNVL_DN_HB';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 5995, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='VSH S-5 REP' AND section='CSMT-PNVL' AND line='DN HB'), 'VSH S-5 REP', 'VSH PF', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_PNVL_DN_HB';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 6195, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='MNKD S-22 REP' AND section='CSMT-PNVL' AND line='UP HB'), 'MNKD S-22 REP', 'MNKD PF', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_PNVL_UP_HB';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 4695, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='K-035 REP' AND section='CSMT-KYN' AND line='DN TH'), 'K-035 REP', 'ON GC PF-3', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 5395, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='VK S-5 REP' AND section='CSMT-KYN' AND line='DN TH'), 'VK S-5 REP', 'ON VK PF-3', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, is_active) SELECT sec.id, 8795, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='K-4001 REP' AND section='CSMT-KYN' AND line='DN TH'), 'K-4001 REP', 'ON MBQ PF-3', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';

SELECT sec.section_code, r.row_order, r.display_signal_no, r.display_location, sg.signal_type
FROM div_signal_book_rows r JOIN div_signal_book_sections sec ON sec.id=r.book_section_id JOIN div_signals sg ON sg.id=r.signal_id
WHERE sg.signal_number LIKE '% REP' AND sg.signal_number IN ('H-09 REP','H-13 REP','H-23 REP','MNKD S-4 REP','VSH S-5 REP','MNKD S-22 REP','K-035 REP','VK S-5 REP','K-4001 REP')
ORDER BY sec.section_code, r.row_order;
