-- Add 11 new CSMT platform starters (PF-8..PF-18) on the DN TH line. Parallel
-- platform signals; appear in CSMT_ML_KR/MMR, CSMT_SUB_ML, KYN_GOODS, KYN_SUB
-- via the shared CSMT_KYN_DN_TH section (rows 508-588, after CSMT S-7 / before S-45).
-- Additive; local then prod. Re-run magnet backfill after (magnet_id starts NULL).

INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-8', 'CSMTS8', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-8 STR', 'Manual', 'Starter', 'Right', 'Unknown', 1, 0, 0, 0, 0, 0, 1, 0, 0, NULL, NULL, NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-9', 'CSMTS9', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-9 STR', 'Manual', 'Starter', 'Right', 'Unknown', 1, 0, 0, 0, 0, 0, 1, 0, 0, NULL, NULL, NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-10', 'CSMTS10', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-10 STR', 'Manual', 'Starter', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 1, 0, 1, 'RI: R1= CSMT S-62', 'Book shows one right arm on top of vertical stem', NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-11', 'CSMTS11', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-11 STR', 'Manual', 'Starter', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 1, 0, 1, 'RI: R1= CSMT S-62', 'Book shows one right arm on top of vertical stem', NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-12', 'CSMTS12', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-12 STR', 'Manual', 'Starter', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 1, 1, 1, 'RI: L1= CSMT S-62; R1= CSMT S-59', 'Book shows one left and one right arm on top of vertical stem', NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-13', 'CSMTS13', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-13 STR', 'Manual', 'Starter', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 1, 1, 1, 'RI: L1= CSMT S-62; R1= CSMT S-59', 'Book shows one left and one right arm on top of vertical stem', NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-14', 'CSMTS14', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-14 STR', 'Manual', 'Starter', 'Right', 'Unknown', 1, 0, 0, 0, 0, 0, 1, 1, 1, 'RI: L1= CSMT S-62; R1= CSMT S-59', 'Book shows one left and one right arm on top of vertical stem', NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-15', 'CSMTS15', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-15 STR', 'Manual', 'Starter', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 1, 1, 1, 'RI: L1= MZN S-5; R1= CSMT S-59', 'Book shows one left and one right arm on top of vertical stem', NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-16', 'CSMTS16', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-16 STR', 'Manual', 'Starter', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 1, 0, 0, NULL, NULL, NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-17', 'CSMTS17', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-17 STR', 'Manual', 'Starter', 'Left', 'Unknown', 0, 0, 1, 0, 0, 0, 1, 0, 0, NULL, NULL, NULL, 1);
INSERT INTO div_signals (signal_number, normalized_signal_number, station_code, station_name, section, line, direction, location_text, signal_type, signal_function, placement, on_curve, is_rhs, is_ext_rhs, is_lhs, is_ext_lhs, has_legend_board, has_calling_on, has_shunt_signal, ri_left_arms, ri_right_arms, book_description, route_indicator_notes, visibility_distance_m, is_active) VALUES ('CSMT S-18', 'CSMTS18', 'CSMT', 'CSMT', 'CSMT-KYN', 'DN TH', 'DN', 'PF-18 STR', 'Manual', 'Starter', 'Right', 'Unknown', 1, 0, 0, 0, 0, 0, 1, 0, 0, NULL, NULL, NULL, 1);

-- book rows in CSMT_KYN_DN_TH
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 508, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-8' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-8', 'PF-8 STR', NULL, 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 516, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-9' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-9', 'PF-9 STR', NULL, 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 524, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-10' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-10', 'PF-10 STR', 'RI: R1= CSMT S-62', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 532, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-11' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-11', 'PF-11 STR', 'RI: R1= CSMT S-62', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 540, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-12' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-12', 'PF-12 STR', 'RI: L1= CSMT S-62; R1= CSMT S-59', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 548, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-13' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-13', 'PF-13 STR', 'RI: L1= CSMT S-62; R1= CSMT S-59', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 556, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-14' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-14', 'PF-14 STR', 'RI: L1= CSMT S-62; R1= CSMT S-59', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 564, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-15' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-15', 'PF-15 STR', 'RI: L1= MZN S-5; R1= CSMT S-59', 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 572, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-16' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-16', 'PF-16 STR', NULL, 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 580, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-17' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-17', 'PF-17 STR', NULL, 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';
INSERT INTO div_signal_book_rows (book_section_id, row_order, row_type, signal_id, display_signal_no, display_location, display_description, is_active) SELECT sec.id, 588, 'SIGNAL', (SELECT id FROM div_signals WHERE signal_number='CSMT S-18' AND section='CSMT-KYN' AND line='DN TH'), 'CSMT S-18', 'PF-18 STR', NULL, 1 FROM div_signal_book_sections sec WHERE sec.section_code='CSMT_KYN_DN_TH';

SELECT sg.signal_number, sg.placement, sg.is_rhs, sg.is_lhs, sg.ri_left_arms, sg.ri_right_arms, r.row_order, r.display_location
FROM div_signals sg JOIN div_signal_book_rows r ON r.signal_id=sg.id
WHERE sg.signal_number LIKE 'CSMT S-1%' AND sg.line='DN TH' AND CAST(SUBSTRING_INDEX(sg.signal_number,'-',-1) AS UNSIGNED) BETWEEN 8 AND 18
ORDER BY r.row_order;
