-- Fresh import of div_trains from div_trains_stations.csv
-- Generated: 2026-05-24T05:19:20.834Z

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE div_train_stops;
TRUNCATE TABLE div_trains;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('10103', 'Mandovi Express', 'DN', 'CSMT', 'RN', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('10104', 'Mandovi Express', 'UP', 'RN', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('10105', 'DIVA-SAWANTWADI Passenger', 'DN', 'DIVA', 'ROHA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('10106', 'DIVA-SAWANTWADI EXP', 'UP', 'ROHA', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('10115', 'Bandra-Madgaon express', 'DN', 'BSR', 'RN', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('10116', 'Bandra-Madgaon express', 'DN', 'BSR', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11001', 'NANDIGRAM EXP', 'DN', 'CSMT', 'MMR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11002', 'NANDIGRAM EXP', 'UP', 'MMR', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11003', 'TUTARI EXP', 'DN', 'DR', 'RN', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11004', 'TUTARI EXP', 'UP', 'ROHA', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11005', 'CHALUKYA EXP', 'DN', 'DR', 'PUNE', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11006', 'CHALUKYA EXP', 'UP', 'PUNE', 'DR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11007', 'DECCAN EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11008', 'DECCAN EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11009', 'SINHAGAD EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11010', 'SINHAGAD EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11011', 'CSMT-DHI EXP', 'DN', 'CSMT', 'MMR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11012', 'CSMT-DHI EXP', 'UP', 'MMR', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11013', 'LTT-CBE Coimbatore express', 'DN', 'LTT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11014', 'LTT-CBE Coimbatore express', 'UP', 'PUNE', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11015', 'LTT-SHC AMRIT BHARAT', 'DN', 'LTT', 'IGP', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11016', 'LTT-SHC AMRIT BHARAT', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11017', 'LTT-KIK EXP', 'DN', 'LTT', 'PUNE', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11018', 'LTT-KIK EXP', 'UP', 'PUNE', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11019', 'KONARK EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11020', 'KONARK EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11021', 'DR-TEN EXP', 'DN', 'DR', 'PUNE', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11022', 'DR-TEN EXP', 'UP', 'PUNE', 'DR', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11027', 'DR-STR-DR EXP', 'DN', 'DR', 'PUNE', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11028', 'DR-STR-DR EXP', 'UP', 'PUNE', 'DR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11029', 'KOYNA EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11030', 'KOYNA EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11031', 'Alipurdaur AB express', 'DN', 'PNVL', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11032', 'Alipurdaur AB express', 'UP', 'IGP', 'PNVL', 'SAT');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11035', 'SHARAVATI EXP', 'DN', 'DR', 'PUNE', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11036', 'SHARAVATI EXP', 'UP', 'PUNE', 'DR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11041', 'DR-SNSI EXP', 'DN', 'DR', 'PUNE', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11042', 'DR-SNSI EXP', 'UP', 'PUNE', 'DR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11049', 'ADI-KOP-ADI EXP', 'UP', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11050', 'ADI-KOP-ADI EXP', 'UP', 'PUNE', 'BSR', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11055', 'LTT-GKP GODAN EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11056', 'LTT-GKP GODAN EXP', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11057', 'CSMT-ASR EXP', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11058', 'CSMT-ASR EXP', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11059', 'LTT-CPR EXP', 'DN', 'LTT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11060', 'LTT-CPR EXP', 'UP', 'IGP', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11061', 'LTT-JYG EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11062', 'LTT-JYG EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11071', 'LTT-BUI KAMAYANI EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11072', 'LTT-BUI KAMAYANI EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11079', 'LTT-GKP EXP', 'DN', 'LTT', 'IGP', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11080', 'LTT-GKP EXP', 'UP', 'IGP', 'LTT', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11081', 'LTT-GKP EXP', 'DN', 'LTT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11082', 'LTT-GKP EXP', 'UP', 'IGP', 'LTT', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11087', 'VRL-PUNE-VRL EXP', 'UP', NULL, NULL, '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11088', 'VRL-PUNE-VRL EXP', 'UP', 'PUNE', 'BSR', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11089', 'BGKT-PUNE-BGKT EXP', 'UP', NULL, NULL, '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11090', 'BGKT-PUNE-BGKT EXP', 'UP', 'PUNE', 'BSR', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11091', 'BHUJ-PUNE-BHUJ EXP', 'UP', NULL, NULL, '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11092', 'BHUJ-PUNE-BHUJ EXP', 'UP', 'PUNE', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11099', 'LTT-MAO EXP', 'DN', 'LTT', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11100', 'LTT-MAO EXP', 'UP', 'RN', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11139', 'CSMT-HPT EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11140', 'CSMT-HPT EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11301', 'CSMT-SBC UDYAN EXPRESS', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('11302', 'CSMT-SBC UDYAN EXPRESS', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12051', 'CSMT-MAO JANSHATBDI EXP', 'DN', 'CSMT', 'RN', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12052', 'CSMT-MAO JANSHATBDI EXP', 'UP', 'RN', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12071', 'CSMT-HNL JANSHATBDTI EXP', 'DN', 'CSMT', 'MMR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12072', 'CSMT-HNL JANSHATBDTI EXP', 'UP', 'MMR', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12101', 'LTT-SHM GYANESHWARI EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12102', 'LTT-SHM GYANESHWARI EXP', 'UP', 'IGP', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12105', 'CSMT-G VIDARBHA EXPRESS', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12106', 'CSMT-G VIDARBHA EXPRESS', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12107', 'LTT-ST EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12108', 'LTT-ST EXP', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12109', 'CSMT-MMR PANCHAVATI EXP', 'DN', 'CSMT', 'MMR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12110', 'CSMT-MMR PANCHAVATI EXP', 'UP', 'MMR', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12111', 'CSMT-AMI SF EXP', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12112', 'CSMT-AMI SF EXP', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12115', 'CSMT-SUR SIDDHESHWAR EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12116', 'CSMT-SUR SIDDHESHWAR EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12123', 'CSMT-PUNE DECCAN QUEEN', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12124', 'CSMT-PUNE DECCAN QUEEN', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12125', 'CSMT-PUNE PRAGATI EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12126', 'CSMT-PUNE PRAGATI EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12127', 'CSMT-PUNE INTERCITY EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12128', 'CSMT-PUNE INTERCITY EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12131', 'DR-SNSI EXP', 'DN', 'DR', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12132', 'DR-SNSI EXP', 'UP', 'IGP', 'DR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12133', 'CSMT-MAJN EXP', 'DN', 'CSMT', 'RN', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12134', 'CSMT-MAJN EXP', 'UP', 'RN', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12137', 'CSMT-FZR PUNJAB MAIL', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12138', 'CSMT-FZR PUNJAB MAIL', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12139', 'CSMT-NGP SEVAGRAM EXP', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12140', 'CSMT-NGP SEVAGRAM EXP', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12141', 'LTT-PPTA PATLIPUTRA EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12142', 'LTT-PPTA PATLIPUTRA EXP', 'DN', 'BSR', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12143', 'LTT-SLN EXP', 'DN', 'LTT', 'IGP', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12144', 'LTT-SLN EXP', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12145', 'LTT-PURI EXP', 'DN', 'LTT', 'IGP', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12146', 'LTT-PURI EXP', 'UP', 'IGP', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12151', 'LTT-SHM SAMRASHTA EXP', 'DN', 'LTT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12152', 'LTT-SHM SAMRASHTA EXP', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12153', 'LTT-RKMP EXP', 'DN', 'LTT', 'IGP', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12154', 'LTT-RKMP EXP', 'UP', 'IGP', 'LTT', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12161', 'LTT-AGC LASHKAR EXP', 'DN', 'LTT', 'IGP', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12162', 'LTT-AGC LASHKAR EXP', 'UP', 'IGP', 'LTT', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12163', 'LTT-MAS EXP', 'DN', 'LTT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12164', 'LTT-MAS EXP', 'UP', 'PUNE', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12165', 'LTT-GKR EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12166', 'LTT-GKR EXP', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12167', 'LTT-BNPRS EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12168', 'LTT-BNPRS EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12171', 'LTT-Haridwar Superfast express', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12172', 'LTT-Haridwar Superfast express', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12173', 'LTT-MBDP UDYOG NAGRI EXP', 'DN', 'LTT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12174', 'LTT-MBDP UDYOG NAGRI EXP', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12187', 'CSMT-JBP GARIB RATH', 'UP', 'IGP', 'CSMT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12188', 'CSMT-JBP GARIB RATH', 'DN', 'CSMT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12201', 'LTT-TVCN GARIB RATH', 'DN', 'LTT', 'RN', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12202', 'LTT-TVCN GARIB RATH', 'UP', 'RN', 'LTT', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12217', 'CDG-TVCN-CDG KERLA S KRANTI EXP', 'UP', 'RN', 'BSR', '2.7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12218', 'CDG-TVCN-CDG KERLA S KRANTI EXP', 'DN', 'BSR', 'RN', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12219', 'LTT-SC DURONTO EXP', 'DN', 'LTT', 'PUNE', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12220', 'LTT-SC DURONTO EXP', 'UP', 'PUNE', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12223', 'LTT-ERS DURONTO EXP', 'DN', 'LTT', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12224', 'LTT-ERS DURONTO EXP', 'UP', 'RN', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12261', 'CSMT-HWH CSMT DURONTO EXP', 'DN', 'CSMT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12262', 'CSMT-HWH CSMT DURONTO EXP', 'UP', 'IGP', 'CSMT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12263', 'NZM-PUNE-NZM DURNTO EXP', 'UP', 'PUNE', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12264', 'NZM-PUNE-NZM DURNTO EXP', 'UP', NULL, NULL, '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12283', 'NZM-ERS-NZM DURONTO EXP', 'UP', 'RN', 'BSR', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12284', 'NZM-ERS-NZM DURONTO EXP', 'UP', 'BSR', 'RN', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12289', 'CSMT-NGP DURONTO EXP', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12290', 'CSMT-NGP DURONTO EXP', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12293', 'LTT-PRY-LTT DURONTO EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12294', 'LTT-PRY-LTT DURONTO EXP', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12297', 'ADI-PUNE-ADI DURONTO EXP', 'UP', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12298', 'ADI-PUNE-ADI DURONTO EXP', 'UP', 'PUNE', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12321', 'CSMT-HWH KOLKATA MAIL', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12322', 'CSMT-HWH KOLKATA MAIL', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12335', 'LTT-BGP EXP', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12336', 'LTT-BGP EXP', 'DN', 'LTT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12361', 'CSMT-ASN EXP', 'UP', 'IGP', 'CSMT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12362', 'CSMT-ASN EXP', 'DN', 'CSMT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12431', 'NZM-TVC-NZM RAJDHANI EXP', 'UP', 'RN', 'BSR', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12432', 'NZM-TVC-NZM RAJDHANI EXP', 'DN', 'BSR', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12449', 'CDG-MAO-CDG GOA SMPRK KRANT', 'UP', 'RN', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12450', 'CDG-MAO-CDG GOA SMPRK KRANT', 'DN', 'BSR', 'RN', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12483', 'ASR-TVCN-ASR EXP', 'UP', 'RN', 'BSR', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12484', 'ASR-TVCN-ASR EXP', 'DN', 'BSR', 'RN', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12493', 'NZM-MRJ-NZM DARSHAN EXPRESS', 'UP', 'PUNE', 'BSR', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12494', 'NZM-MRJ-NZM DARSHAN EXPRESS', 'DN', NULL, NULL, '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12533', 'CSMT-GTNA CSMT PUSHPAK EXP', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12534', 'CSMT-GTNA CSMT PUSHPAK EXP', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12545', 'LTT-RXL KARMBHUMI EXP', 'UP', 'IGP', 'LTT', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12546', 'LTT-RXL KARMBHUMI EXP', 'DN', 'LTT', 'IGP', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12597', 'CSMT-GKP ANTODAYA EXP', 'UP', 'IGP', 'CSMT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12598', 'CSMT-GKP ANTODAYA EXP', 'DN', 'CSMT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12617', 'NZM-ERS-NZM MANGLA LKSDP EXP', 'UP', 'RN', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12618', 'NZM-ERS-NZM MANGLA LKSDP EXP', 'DN', 'IGP', 'RN', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12619', 'LTT-MAQ MATSYAGANDHA EXP', 'DN', 'LTT', 'RN', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12620', 'LTT-MAQ MATSYAGANDHA EXP', 'UP', 'RN', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12701', 'CSMT-HYB HUSSAINSAGAR EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12702', 'CSMT-HYB HUSSAINSAGAR EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12741', 'PNBE-VSG-PNBE EXP', 'UP', 'RN', 'IGP', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12742', 'PNBE-VSG-PNBE EXP', 'DN', 'BSR', 'KYN', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12755', 'BVC-COA-BVC EXP', 'UP', NULL, NULL, '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12756', 'BVC-COA-BVC EXP', 'DN', NULL, NULL, '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12809', 'CSMT-HWH HOWRAH MAIL', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12810', 'CSMT-HWH HOWRAH MAIL', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12811', 'LTT-Hatia SF Express', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12812', 'LTT-Hatia SF Express', 'UP', 'IGP', 'LTT', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12859', 'LTT-HTE EXP', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12860', 'LTT-HTE EXP', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12869', 'CSMT-HWH GITANJALI EXP', 'DN', 'CSMT', 'IGP', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12870', 'CSMT-HWH GITANJALI EXP', 'UP', 'IGP', 'CSMT', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12879', 'LTT-BBS EXP', 'DN', 'LTT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12880', 'LTT-BBS EXP', 'UP', 'IGP', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12939', 'JP-PUNE-JP EXP', 'UP', 'PUNE', 'BSR', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12940', 'JP-PUNE-JP EXP', 'DN', NULL, NULL, '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12977', 'All-ERS-All MARU SAGAR EXP', 'UP', 'RN', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('12978', 'All-ERS-All MARU SAGAR EXP', 'DN', 'BSR', 'RN', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('13201', 'LTT-RGD EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('13202', 'LTT-RGD EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('14313', 'LTT-BE EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('14314', 'LTT-BE EXP', 'UP', 'IGP', 'LTT', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('14805', 'BME-YPR-BME EXP', 'UP', 'PUNE', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('14806', 'BME-YPR-BME EXP', 'DN', NULL, NULL, '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15017', 'LTT-GKR KASHI EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15018', 'LTT-GKR KASHI EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15065', 'PNVL-GKP-PNVL EXP', 'UP', 'IGP', 'PNVL', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15066', 'PNVL-GKP-PNVL EXP', 'DN', 'PNVL', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15181', 'LTT-MAU EXPRESS', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15182', 'LTT-MAU EXPRESS', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15267', 'LTT-RXL ANTYODAY EXP', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15268', 'LTT-RXL ANTYODAY EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15647', 'LTT-GHY EXPRES EXP', 'DN', 'LTT', 'IGP', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15648', 'LTT-GHY EXPRES EXP', 'UP', 'IGP', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15659', 'LTT-AGT-LTT AC SF EXP', 'DN', 'LTT', 'IGP', 'SUN');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15660', 'LTT-AGT-LTT AC SF EXP', 'UP', 'IGP', 'LTT', 'SAT');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15945', 'LTT-DBRG EXP', 'DN', 'LTT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('15946', 'LTT-DBRG EXP', 'UP', 'IGP', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16209', 'All-MYS-All EXP', 'DN', 'BSR', 'PUNE', '5.7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16210', 'All-MYS-All EXP', 'UP', 'PUNE', 'BSR', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16311', 'SGNR-TVCN express', 'UP', 'BSR', 'RN', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16312', 'SGNR-TVCN express', 'UP', 'RN', 'BSR', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16331', 'LTT-TVC EXP', 'DN', 'LTT', 'PUNE', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16332', 'LTT-TVC EXP', 'UP', 'PUNE', 'LTT', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16333', 'VRL-TVC-VRL EXP', 'DN', 'BSR', 'RN', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16334', 'VRL-TVC-VRL EXP', 'UP', 'RN', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16335', 'GIMB-NCJ-GIMB EXP', 'DN', 'BSR', 'RN', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16336', 'GIMB-NCJ-GIMB EXP', 'UP', 'RN', 'BSR', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16337', 'OKHA-ERS-OKHA EXP', 'DN', 'BSR', 'RN', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16338', 'OKHA-ERS-OKHA EXP', 'UP', 'RN', 'BSR', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16339', 'LTT-NCJ EXP', 'DN', 'LTT', 'PUNE', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16340', 'LTT-NCJ EXP', 'UP', 'PUNE', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16345', 'LTT-TVC NETRAVATI EXP', 'DN', 'LTT', 'ROHA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16346', 'LTT-TVC NETRAVATI EXP', 'UP', 'ROHA', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16351', 'LTT-NCJ EXP', 'DN', 'LTT', 'PUNE', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16352', 'LTT-NCJ EXP', 'UP', 'PUNE', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16531', 'All-SBC-All GARIB NAWAJ EXP', 'UP', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16532', 'All-SBC-All GARIB NAWAJ EXP', 'UP', 'PUNE', 'BSR', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16533', 'BGKT-SBC-BGKT EXP', 'UP', NULL, NULL, '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16534', 'BGKT-SBC-BGKT EXP', 'UP', 'PUNE', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16553', 'Bengaluru-LTT express', 'UP', 'PUNE', 'LTT', 'WED');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16554', 'Bengaluru-LTT express', 'DN', 'LTT', 'PUNE', 'WED');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16587', 'BKN-YPR-BKN EXP', 'UP', 'PUNE', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16588', 'BKN-YPR-BKN EXP', 'DN', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16613', 'RJT-CBE-RJT EXP', 'UP', NULL, NULL, '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('16614', 'RJT-CBE-RJT EXP', 'DN', NULL, NULL, '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17057', 'CSMT-LPI DEVAGIRI EXP', 'DN', 'CSMT', 'MMR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17058', 'CSMT-LPI DEVAGIRI EXP', 'UP', 'MMR', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17221', 'LTT-COA EXP', 'UP', 'PUNE', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17222', 'LTT-COA EXP', 'DN', 'LTT', 'PUNE', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17317', 'DR-UBL-DR EXP', 'UP', 'PUNE', 'DR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17318', 'DR-UBL-DR EXP', 'DN', 'DR', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17411', 'CSMT-KOP MAHALAXMI EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17412', 'CSMT-KOP MAHALAXMI EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17611', 'Nanded Rajya rani express', 'UP', 'MMR', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17612', 'Nanded Rajya rani express', 'DN', 'CSMT', 'MMR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17613', 'PNVL-NED-PNVL EXP', 'UP', 'PNVL', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17614', 'PNVL-NED-PNVL EXP', 'UP', 'PUNE', 'PNVL', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17617', 'CSMT-NED TAPOVAN EXP', 'DN', 'CSMT', 'MMR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17618', 'CSMT-NED TAPOVAN EXP', 'UP', 'MMR', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17665', 'Nanded LTT express', 'UP', 'IGP', 'LTT', 'TUE');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17666', 'Nanded LTT express', 'DN', 'LTT', 'IGP', 'TUE');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17667', 'Nanded LTT express', 'UP', 'IGP', 'LTT', 'THU');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('17668', 'Nanded LTT express', 'DN', 'LTT', 'IGP', 'THU');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('18029', 'LTT-SHM EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('18030', 'LTT-SHM EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('18519', 'LTT-VSKP EXP', 'UP', 'PUNE', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('18520', 'LTT-VSKP EXP', 'DN', 'LTT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('18609', 'LTT-RNC EXP', 'UP', 'IGP', 'LTT', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('18610', 'LTT-RNC EXP', 'DN', 'LTT', 'IGP', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19259', 'BVC-TVCN-BVC EXP', 'UP', 'RN', 'BSR', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19260', 'BVC-TVCN-BVC EXP', 'DN', 'BSR', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19567', 'OKHA-TN-OKHA VIVEK EXPRESS', 'UP', 'PUNE', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19568', 'OKHA-TN-OKHA VIVEK EXPRESS', 'DN', NULL, NULL, '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19577', 'JAM-TEN-JAM EXP', 'UP', 'RN', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19578', 'JAM-TEN-JAM EXP', 'DN', NULL, NULL, '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19667', 'UDZ-MYS-UDZ HUMSAFAR EXP', 'UP', NULL, NULL, '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('19668', 'UDZ-MYS-UDZ HUMSAFAR EXP', 'UP', 'PUNE', 'BSR', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20103', 'LTT-GKP EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20104', 'LTT-GKP EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20111', 'CSMT-MAO KONKAN KANYA EXP', 'DN', 'CSMT', 'RN', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20112', 'CSMT-MAO KONKAN KANYA EXP', 'UP', 'RN', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20475', 'BKN-MRJ-BKN SF EXP', 'UP', NULL, NULL, '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20476', 'BKN-MRJ-BKN SF EXP', 'UP', 'PUNE', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20495', 'BKN-MRJ-BKN SF EXP', 'UP', NULL, NULL, 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20496', 'BKN-MRJ-BKN SF EXP', 'UP', 'PUNE', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20667', 'Yashvantpur-Jaipur express', 'UP', 'PUNE', 'BSR', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20668', 'Yashvantpur-Jaipur express', 'DN', NULL, NULL, '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20685', 'Gandhidham-Bengaluru SF express', 'UP', 'BSR', 'PUNE', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20686', 'Gandhidham-Bengaluru SF express', 'UP', 'PUNE', 'BSR', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20693', 'Jodhpur-Bengaluru SF express', 'UP', 'BSR', 'PUNE', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20694', 'Jodhpur-Bengaluru SF express', 'UP', 'PUNE', 'BSR', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20705', 'CSMT-J VANDE BHARAT', 'UP', 'MMR', 'CSMT', 'XWED');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20706', 'CSMT-J VANDE BHARAT', 'DN', 'CSMT', 'MMR', 'XTHU');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20821', 'SRC-PUNE-SRC HUMSAFAR EXP', 'UP', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20822', 'SRC-PUNE-SRC HUMSAFAR EXP', 'DN', 'BSR', 'KYN', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20909', 'TVCN-Porbundar SF express', 'UP', 'RN', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20910', 'TVCN-Porbundar SF express', 'DN', 'BSR', 'RN', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20915', 'Charlapalli-Indore Humsafar Express', 'UP', 'PUNE', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20916', 'Charlapalli-Indore Humsafar Express', 'DN', 'BSR', 'PUNE', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20919', 'Chennai-ekta nagar SF express', 'UP', 'PUNE', 'BSR', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20920', 'Chennai-ekta nagar SF express', 'DN', NULL, NULL, '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20923', 'Thirunelveli-Gandhidham Humsafar express', 'UP', 'RN', 'BSR', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20924', 'Thirunelveli-Gandhidham Humsafar express', 'DN', 'BSR', 'RN', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20931', 'TVCN-Indore SF express', 'UP', 'RN', 'BSR', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20932', 'TVCN-Indore SF express', 'DN', 'BSR', 'RN', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20953', 'MAS ADI EXPRESS', 'UP', 'PUNE', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20954', 'Chennai-ADI SF express', 'DN', NULL, NULL, '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20967', 'Porbundar-secundarabad SF express', 'UP', NULL, NULL, '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('20968', 'Porbundar-secundarabad SF express', 'DN', NULL, NULL, '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22101', 'LTT-MDU EXP', 'DN', 'LTT', 'PUNE', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22102', 'LTT-MDU EXP', 'UP', 'PUNE', 'LTT', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22103', 'LTT-AYC EXP', 'DN', 'LTT', 'IGP', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22104', 'LTT-AYC EXP', 'UP', 'IGP', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22105', 'CSMT-PUNE INDRAYANI EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22106', 'CSMT-PUNE INDRAYANI EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22107', 'CSMT-LUR-CSMT EXP', 'DN', 'CSMT', 'PUNE', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22108', 'CSMT-LUR-CSMT EXP', 'UP', 'PUNE', 'CSMT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22109', 'LTT-BPQ EXP', 'DN', 'LTT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22110', 'LTT-BPQ EXP', 'UP', 'IGP', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22113', 'LTT-TVCN SF EXP', 'DN', 'LTT', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22114', 'LTT-TVCN SF EXP', 'UP', 'RN', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22115', 'LTT-KRMI EXP', 'DN', 'LTT', 'RN', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22116', 'LTT-KRMI EXP', 'UP', 'RN', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22119', 'LTT-MAO-LTT AC EXP', 'DN', 'LTT', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22120', 'LTT-MAO-LTT AC EXP', 'UP', 'RN', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22121', 'LTT LKO AC EXP', 'DN', 'LTT', 'IGP', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22122', 'LTT LKO AC EXP', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22129', 'LTT-Ayodhya cantt SF express', 'DN', 'LTT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22130', 'LTT-Ayodhya cantt SF express', 'UP', 'IGP', 'LTT', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22143', 'CSMT-BIDAR EXP', 'DN', 'CSMT', 'PUNE', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22144', 'CSMT-BIDAR EXP', 'UP', 'PUNE', 'CSMT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22147', 'DR-SNSI-DR SF EXP', 'DN', 'DR', 'IGP', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22148', 'DR-SNSI-DR SF EXP', 'UP', 'IGP', 'DR', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22149', 'PUNE-ERS-PUNE EXP', 'UP', 'RN', 'PUNE', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22150', 'PUNE-ERS-PUNE EXP', 'DN', 'PUNE', 'RN', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22157', 'CSMT-MAS-CSMT EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22158', 'CSMT-MAS-CSMT EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22159', 'CSMT-MAS-CSMT EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22160', 'CSMT-MAS-CSMT EXP', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22177', 'CSMT-BNRS MAHANAGARI EXP', 'DN', 'CSMT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22178', 'CSMT-BNRS MAHANAGARI EXP', 'UP', 'IGP', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22179', 'LTT-MAS SF EXPRESS', 'DN', 'LTT', 'PUNE', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22180', 'LTT-BSB CSMT MAHANAGARI EXP', 'UP', 'PUNE', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22183', 'LTT-AYC-LTT SAKET EXPRESS', 'DN', 'LTT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22184', 'LTT-AYC-LTT SAKET EXPRESS', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22185', 'ADI-PUNE-ADI AHIMSA EXP', 'DN', 'BSR', 'PUNE', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22186', 'ADI-PUNE-ADI AHIMSA EXP', 'UP', 'PUNE', 'BSR', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22193', 'GWL-DD-GWL SF EXP', 'UP', 'BSR', 'PUNE', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22194', 'GWL-DD-GWL SF EXP', 'DN', 'BSR', 'PUNE', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22221', 'CSMT-NZM RAJDHANI EXP', 'DN', 'CSMT', 'JL', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22222', 'CSMT-NZM RAJDHANI EXP', 'UP', 'JL', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22223', 'CSMT-SNSI-CSMT VANDE BHARAT', 'DN', 'CSMT', 'MMR', 'XTUE');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22224', 'CSMT-SNSI-CSMT VANDE BHARAT', 'UP', 'MMR', 'CSMT', 'XTUE');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22225', 'CSMT-SUR-CSMT VANDE BHARAT', 'DN', 'CSMT', 'PUNE', 'XWED');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22226', 'CSMT-SUR-CSMT VANDE BHARAT', 'UP', 'PUNE', 'CSMT', 'XTHU');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22229', 'CSMT-MAO-CSMT VANDE BHARAT', 'DN', 'CSMT', 'RN', 'XFRI');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22230', 'CSMT-MAO-CSMT VANDE BHARAT', 'UP', 'RN', 'CSMT', 'XFRI');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22311', 'Godda-LTT SF express', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22312', 'Godda-LTT SF express', 'DN', 'LTT', 'IGP', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22357', 'LTT-Gaya SF express', 'DN', 'LTT', 'IGP', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22358', 'LTT-Gaya SF express', 'UP', 'IGP', 'LTT', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22359', 'CSMT-PNBE SF EXP', 'UP', 'IGP', 'CSMT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22360', 'CSMT-PNBE SF EXP', 'DN', 'CSMT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22413', 'NZM-MAO-NZM RAJDHANI EXP', 'UP', 'RN', 'BSR', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22414', 'NZM-MAO-NZM RAJDHANI EXP', 'DN', 'BSR', 'RN', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22475', 'HSR-CBE-HSR AC EXP', 'UP', 'BSR', 'RN', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22476', 'HSR-CBE-HSR AC EXP', 'UP', 'RN', 'BSR', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22497', 'SGNR-TPI-SGNR HUMSAFAR EXP', 'UP', NULL, NULL, '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22498', 'SGNR-TPI-SGNR HUMSAFAR EXP', 'UP', 'PUNE', 'BSR', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22511', 'LTT-KYQ KARMABHOOMI EXP', 'DN', 'LTT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22512', 'LTT-KYQ KARMABHOOMI EXP', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22537', 'LTT-GKP KUSHINAGAR EXP', 'UP', 'IGP', 'LTT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22538', 'LTT-GKP KUSHINAGAR EXP', 'DN', 'LTT', 'IGP', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22553', 'LTT-RXL ANTYODAY EXP', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22554', 'LTT-RXL ANTYODAY EXP', 'DN', 'LTT', 'IGP', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22583', 'LTT-CPR ANTYODAY EXP', 'UP', 'IGP', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22584', 'LTT-CPR ANTYODAY EXP', 'DN', 'LTT', 'IGP', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22629', 'LTT-TEN-DR EXP', 'DN', 'LTT', 'RN', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22630', 'LTT-TEN-LTT EXP', 'UP', 'RN', 'LTT', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22633', 'TVC-Hazrat Nizamuddin SF express', 'UP', 'RN', 'BSR', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22634', 'TVC-Hazrat Nizamuddin SF express', 'DN', 'BSR', 'RN', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22653', 'NZM-TVC-NZM SF EXP', 'UP', 'BSR', 'ROHA', '7');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22654', 'NZM-TVC-NZM SF EXP', 'DN', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22655', 'Ernakulan jn-Hazrat Nizamuddin SF express', 'UP', 'BSR', 'ROHA', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22656', 'Ernakulan jn-Hazrat Nizamuddin SF express', 'DN', NULL, NULL, '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22659', 'TVCN-Rishikesh SF express', 'UP', 'RN', 'BSR', '6');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22660', 'TVCN-Rishikesh SF express', 'DN', 'BSR', 'RN', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22717', 'Rajkot-secundarabad SF express', 'UP', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22718', 'Rajkot-secundarabad SF express', 'DN', NULL, NULL, '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22731', 'HYD-MUMBAI SF EXPRESS', 'UP', 'PUNE', 'CSMT', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22732', 'NZM-TVC-NZM EXP', 'DN', 'CSMT', 'PUNE', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22847', 'CSMT-HWH SF EXP', 'UP', 'IGP', 'LTT', '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22848', 'CSMT-HWH SF EXP', 'DN', 'LTT', 'IGP', '2');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22865', 'LTT-BBS SF EXP', 'DN', 'LTT', 'IGP', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22866', 'LTT-BBS SF EXP', 'UP', 'IGP', 'LTT', '3');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22907', 'Madgaon-Hapa SF express', 'UP', 'RN', 'BSR', '5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22908', 'Madgaon-Hapa SF express', 'DN', 'BSR', 'RN', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22919', 'ADI HUMSAFAR', 'UP', 'PUNE', 'BSR', '4');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22920', 'ADI-MAS Humsafar express', 'DN', NULL, NULL, '1');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22943', 'DAUND INDORE EXPRESS', 'UP', 'PUNE', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('22944', 'CSMT-PNBE HUMSAFAR EXP', 'DN', NULL, NULL, 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('50103', 'DIVA-RATNAGIRI-DIVA PASS', 'DN', 'DIVA', 'ROHA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('50104', 'DIVA-RATNAGIRI-DIVA PASS', 'UP', 'ROHA', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61002', 'Dombivali-Boisar MEMU', 'DN', 'DI', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61004', 'DIVA-BSR-DIVA MEMU', 'DN', 'DIVA', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61003', 'BSR-DIVA MEMU', 'DN', 'BSR', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61005', 'BSR-DIVA MEMU', 'DN', 'BSR', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61006', 'DIVA-BSR-DIVA MEMU', 'DN', 'DIVA', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61007', 'BSR-DIVA MEMU', 'DN', 'BSR', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61008', 'DIVA-BSR-DIVA MEMU', 'DN', 'DIVA', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61009', 'BSR-DIVA MEMU', 'DN', 'BSR', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61010', 'ROHA-DIVA MEMU', 'UP', 'ROHA', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61011', 'DIVA-ROHA MEMU', 'DN', 'DIVA', 'ROHA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61012', 'ROHA-DIVA MEMU', 'UP', 'ROHA', 'DIVA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61013', 'DIVA-ROHA MEMU', 'DN', 'DIVA', 'ROHA', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61015', 'DIVA-ROHA MEMU', 'DN', 'DIVA', 'ROHA', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61016', 'ROHA-DIVA MEMU', 'UP', 'ROHA', 'DIVA', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61017', 'DIVA-PNVL MEMU', 'DN', 'DIVA', 'PNVL', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61018', 'PNVL-DIVA MEMU', 'UP', 'PNVL', 'DIVA', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61019', 'DIVA-PEN MEMU', 'DN', 'DIVA', 'PEN', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61020', 'PEN-DIVA MEMU', 'UP', 'PEN', 'DIVA', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61021', 'BSR-DIVA MEMU', 'DN', 'BSR', 'DIVA', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61022', 'DIVA-BSR MEMU', 'UP', 'DIVA', 'BSR', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61023', 'DIVA-PEN MEMU', 'DN', 'DIVA', 'PEN', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61024', 'PEN-DIVA MEMU', 'UP', 'PEN', 'DIVA', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('61025', 'DIVA-PEN MEMU', 'DN', 'DIVA', 'PEN', '1,2,3,4,5');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('69161', 'DRD-PNVL MEMU', 'UP', 'PNVL', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('69164', 'DRD-PNVL MEMU', 'DN', 'BSR', 'PNVL', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('69165', 'Panvel-Vasai road MEMU', 'UP', 'PNVL', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('69166', 'Panvel-Vasai road MEMU', 'DN', 'BSR', 'PNVL', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('69167', 'Panvel-Vasai road MEMU', 'UP', 'PNVL', 'BSR', 'DAILY');
INSERT INTO div_trains (train_no, train_name, direction, from_station, to_station, run_days) VALUES ('69168', 'Panvel-Vasai road MEMU', 'DN', 'BSR', 'PNVL', 'DAILY');

-- Verify
SELECT COUNT(*) as total_trains FROM div_trains;
SELECT from_station, COUNT(*) as cnt FROM div_trains WHERE from_station IS NOT NULL GROUP BY from_station ORDER BY cnt DESC;
